


import { centroCostoPropietarioObj, centroCostoTenenciaObj, estadoObj, fechaGeneracionObj } from "./common";


export const filters = [
    {
      label: 'Descripción',
      type: 'text',
      wsField: 'descripcion',
    },
    {
      label: 'Detalles de la plantilla',
      type: 'text',
      wsField: 'valor',
      listCompare: [{ id: 'contiene', descripcion: 'contiene' }],
    },
    {
      label: 'Etiquetas',
      type: 'list',
      wsField: 'etiqueta',
      listValues: [
        { id: '1', descripcion: '306' },
        { id: '2', descripcion: 'LO' },
        { id: '3', descripcion: 'Caja Cheques de Camara' },
        { id: '4', descripcion: 'Caja LO' },
        { id: '5', descripcion: 'Caja Legajo de Cheque' },
        { id: '6', descripcion: 'Caja TC Carpeta No Vigente' },
        { id: '7', descripcion: 'Caja CC Carpeta No Vigente' },
        { id: '8', descripcion: 'Caja CA Carpeta No Vigente' },
        { id: '9', descripcion: 'Caja PP Carpeta No Vigente' },
        { id: '10', descripcion: 'Caja PQ Carpeta No Vigente' },
        { id: '11', descripcion: 'Caja Extractos' },
        { id: '12', descripcion: 'Caja Otra Documentacion' },
        { id: '13', descripcion: 'Carpeta Hipoteca Securitizable' },
        { id: '14', descripcion: 'Solicitudes Galicia Ahora' },
        { id: '15', descripcion: 'Caja Area Central F1102' },
        { id: '16', descripcion: 'Caja Area Central' },
        { id: '17', descripcion: 'Carpeta de Prenda' },
        { id: '18', descripcion: 'Carpeta de Individuos' },
        { id: '19', descripcion: 'Sobre de Actualizaciones' },
        { id: '20', descripcion: 'Caja pesificacion' },
        { id: '21', descripcion: 'OPERACIONES CON DETALLE' },
        { id: '22', descripcion: 'CAJA WF' },
        { id: '23', descripcion: 'CONTRATOS Y PODERES CON DETALLE' },
        { id: '24', descripcion: 'FORMULARIOS DE ACTUALIZACION DE DATOS HABERES' },
        { id: '25', descripcion: 'LEGAJOS CON PROD NO IMPORT DEL WORKFLOW VIEJO' },
        { id: '26', descripcion: 'ALTA DE COMERCIO' },
        { id: '27', descripcion: 'FORMULARIOS SEGUROS DE ACCIDENTES PERSONALES' },
        { id: '202', descripcion: 'Documentos de proyecto' },
        { id: '203', descripcion: 'Documentos personales' },
        { id: '204', descripcion: 'Interbanking Legajos Diarios' },
        { id: '205', descripcion: 'GFGSA' },
        { id: '206', descripcion: 'legajo de clientes' },
        { id: '207', descripcion: 'CARPETAS RECHAZADAS 2012/2013' },
        { id: '208', descripcion: 'CHEQUES CJE GALICIA + O/BCOS 48 HS' },
        { id: '209', descripcion: 'depuracion empresas' },
        { id: '210', descripcion: '31/03/2016 al 26/04/2016' },
      ],
      listCompare: [
        { id: 'contiene', descripcion: 'contiene' },
        { id: 'no contiene', descripcion: 'no contiene' },
      ],
    },
    {
      label: 'Fecha documentación',
      type: 'date',
      wsField: 'fechaDocumentacion',
    },
    fechaGeneracionObj,
    {
      label: 'Fecha vencimiento',
      type: 'date',
      wsField: 'fechaVencimiento',
    },
    {
      label: 'Número de lote',
      type: 'number',
      wsField: 'numeroLote',
    },
    {
      
      label: 'Número de caja',
      type: 'number',
      wsField: 'id',
    },
    centroCostoPropietarioObj,
    centroCostoTenenciaObj,
    estadoObj,
    {
      label: 'Tipo de caja',
      type: 'list',
      wsField: 'idTipoCaja',
      listValues: [
        { id: '1', descripcion: 'Caja genérica' },
        { id: '2', descripcion: 'Caja cheques' },
        { id: '3', descripcion: 'Caja legajos originación' },
        { id: '4', descripcion: 'Caja legajos operativos' },
        { id: '5', descripcion: 'Caja legajos vigentes' },
        { id: '6', descripcion: 'Caja legajos no vigentes' },
        { id: '8', descripcion: 'Biblioratos CAH' },
        { id: '9', descripcion: 'Registros de Firmas' },
        { id: '10', descripcion: 'Legajo Comercial' },
        { id: '11', descripcion: 'Biblioratos UAL' },
        { id: '13', descripcion: 'DIRECTORIO CC 1001 Y 1004' },
        { id: '15', descripcion: 'LIBROS SOCIETARIOS - CONTABLES' },
        { id: '16', descripcion: 'Caja Varios' },
        { id: '17', descripcion: 'Contratos Marco Proveedores' },
        { id: '18', descripcion: 'Legajo Colaboradores' },
        { id: '19', descripcion: 'Caja de Infraestructura de Sucursales' },
      ],
    },
  ];