export const mockSectores = [
  { id: 0, descripcion: 'Sucursal no informada' },
  { id: 1, descripcion: 'BALVANERA' },
  { id: 2, descripcion: 'SAN CRISTOBAL' },
  { id: 3, descripcion: 'ABASTO' },
  { id: 4, descripcion: 'MONSERRAT' },
  { id: 5, descripcion: 'CENTRO' },
  { id: 6, descripcion: 'FLORES' },
  { id: 7, descripcion: 'BOEDO' },
  { id: 8, descripcion: 'CORONEL DIAZ' },
  { id: 9, descripcion: 'SAAVEDRA' },
  { id: 10, descripcion: 'PLAZA SAN MARTIN' },
  { id: 11, descripcion: 'QUINTANA' },
  { id: 12, descripcion: 'VILLA DEL PARQUE' },
  { id: 13, descripcion: 'FLORESTA' },
  { id: 14, descripcion: 'LINIERS' },
  { id: 15, descripcion: 'CONSTITUYENTES' },
  { id: 16, descripcion: 'PARQUE LEZAMA' },
  { id: 17, descripcion: 'JURAMENTO' },
  { id: 18, descripcion: 'ARROYO' },
  { id: 19, descripcion: 'NUÑEZ' },
  { id: 20, descripcion: 'PLAZA ALEMANIA' },
  { id: 21, descripcion: 'COLEGIALES' },
  { id: 22, descripcion: 'PARQUE CHAS' },
  { id: 23, descripcion: 'GALICIA' },
  { id: 24, descripcion: 'PLAZA DE LA REPUBLICA' },
  { id: 25, descripcion: 'VILLA CRESPO' },
  { id: 26, descripcion: 'SAN BENITO PALERMO' },
  { id: 27, descripcion: 'PEDRO GOYENA' },
  { id: 28, descripcion: 'MATADEROS NORTE' },
  { id: 29, descripcion: 'PARQUE CENTENARIO' },
  { id: 30, descripcion: 'VILLA PUEYRREDON' },
  { id: 31, descripcion: 'BARILOCHE' },
  { id: 32, descripcion: 'PALERMO SUD' },
  { id: 33, descripcion: 'VILLA GENERAL MITRE' },
  { id: 34, descripcion: 'VENADO TUERTO' },
  { id: 35, descripcion: 'VILLA DEVOTO' },
  { id: 36, descripcion: 'NUEVA POMPEYA' },
  { id: 37, descripcion: 'PASEO COLON' },
  { id: 38, descripcion: 'AVENIDA DE MAYO' },
  { id: 39, descripcion: 'BARRIO NORTE' },
  { id: 40, descripcion: 'AVELLANEDA' },
  { id: 41, descripcion: 'MARTINEZ' },
  { id: 42, descripcion: 'MORON' },
  { id: 43, descripcion: 'LUJAN' },
  { id: 44, descripcion: 'TEMPERLEY' },
  { id: 45, descripcion: 'GERLI' },
  { id: 46, descripcion: 'SARANDI' },
  { id: 47, descripcion: 'FLORIDA' },
  { id: 48, descripcion: 'ACASSUSO' },
  { id: 49, descripcion: 'SAN ANDRES' },
  { id: 50, descripcion: 'SAENZ PEÑA' },
  { id: 51, descripcion: 'LOMAS DE MARTINEZ' },
  { id: 52, descripcion: 'MERCEDES' },
  { id: 53, descripcion: 'OLIVOS' },
  { id: 54, descripcion: 'LANUS OESTE' },
  { id: 55, descripcion: 'VICENTE LOPEZ' },
  { id: 56, descripcion: 'FLORIDA OESTE' },
  { id: 57, descripcion: 'CIUDADELA' },
  { id: 58, descripcion: 'SAN MARTIN' },
  { id: 59, descripcion: 'MERLO' },
  { id: 60, descripcion: 'ARISTOBULO DEL VALLE' },
  { id: 61, descripcion: 'BANFIELD' },
  { id: 62, descripcion: 'RAMOS MEJIA' },
  { id: 63, descripcion: 'CASTELAR' },
  { id: 64, descripcion: 'AV. CORDOBA' },
  { id: 65, descripcion: 'CHIVILCOY' },
  { id: 66, descripcion: 'JARDIN BOTANICO' },
  { id: 67, descripcion: 'NAZCA' },
  { id: 68, descripcion: 'MICROCENTRO S. MARTIN' },
  { id: 69, descripcion: 'ALMAGRO SUD' },
  { id: 70, descripcion: 'POSADAS' },
  { id: 71, descripcion: 'RESISTENCIA' },
  { id: 72, descripcion: 'FORMOSA' },
  { id: 73, descripcion: 'CORDOBA AEROPUERTO' },
  { id: 74, descripcion: 'GOYA' },
  { id: 75, descripcion: 'ROSARIO' },
  { id: 76, descripcion: 'CORDOBA' },
  { id: 77, descripcion: 'CORRIENTES' },
  { id: 78, descripcion: 'MAR DEL PLATA' },
  { id: 79, descripcion: 'SANTA FE' },
  { id: 80, descripcion: 'PARANA' },
  { id: 81, descripcion: 'MENDOZA' },
  { id: 82, descripcion: 'BAHIA BLANCA' },
  { id: 83, descripcion: 'INDEPENDENCIA' },
  { id: 84, descripcion: 'JUAN B. JUSTO' },
  { id: 85, descripcion: 'BRAGADO' },
  { id: 86, descripcion: 'RECOLETA' },
  { id: 87, descripcion: 'HAEDO' },
  { id: 88, descripcion: 'FLORES NORTE' },
  { id: 89, descripcion: 'TUCUMAN' },
  { id: 90, descripcion: 'REMEDIOS DE ESCALADA' },
  { id: 91, descripcion: 'LOMAS DEL MIRADOR' },
  { id: 92, descripcion: 'TROPEZON' },
  { id: 93, descripcion: 'SAN ANTONIO DE PADUA' },
  { id: 94, descripcion: 'LANUS ESTE' },
  { id: 95, descripcion: 'MUNRO' },
  { id: 96, descripcion: 'ITUZAINGO' },
  { id: 97, descripcion: 'JUNIN' },
  { id: 98, descripcion: 'ARRECIFES' },
  { id: 99, descripcion: 'CATALINAS' },
  { id: 100, descripcion: 'CHACABUCO' },
  { id: 101, descripcion: 'PERGAMINO' },
  { id: 102, descripcion: 'SAN MIGUEL' },
  { id: 103, descripcion: 'AVDA. PELLEGRINI' },
  { id: 104, descripcion: 'CASEROS' },
  { id: 105, descripcion: 'TANDIL' },
  { id: 106, descripcion: 'TRES ARROYOS' },
  { id: 107, descripcion: 'BERNAL' },
  { id: 108, descripcion: 'CASILDA' },
  { id: 109, descripcion: 'SAN FRANCISCO' },
  { id: 110, descripcion: 'OLAVARRIA' },
  { id: 111, descripcion: 'RAFAELA' },
  { id: 112, descripcion: 'SAN JUAN' },
  { id: 113, descripcion: 'CONCORDIA' },
  { id: 114, descripcion: 'GUALEGUAYCHU' },
  { id: 115, descripcion: 'VILLA MARIA' },
  { id: 116, descripcion: 'JUJUY' },
  { id: 117, descripcion: 'SAN NICOLAS' },
  { id: 118, descripcion: 'CAMPANA' },
  { id: 119, descripcion: 'PILAR' },
  { id: 120, descripcion: 'AZUL' },
  { id: 121, descripcion: 'SANTIAGO DEL ESTERO' },
  { id: 122, descripcion: 'QUILMES' },
  { id: 123, descripcion: 'GENERAL PICO' },
  { id: 124, descripcion: 'SAN JUSTO' },
  { id: 125, descripcion: 'LUIS MARIA CAMPOS' },
  { id: 126, descripcion: 'CENTENERA' },
  { id: 127, descripcion: 'UGARTECHE' },
  { id: 128, descripcion: 'BELGRANO SUD' },
  { id: 129, descripcion: 'NEUQUEN' },
  { id: 130, descripcion: 'BELGRANO NORTE' },
  { id: 131, descripcion: 'GRAND BOURG' },
  { id: 132, descripcion: 'FLORENCIO VARELA' },
  { id: 133, descripcion: 'PLAZA GRAND BOURG' },
  { id: 134, descripcion: 'BELGRANO' },
  { id: 135, descripcion: 'PARQUE INDUSTRIAL ESTRELLA' },
  { id: 136, descripcion: 'CABALLITO' },
  { id: 137, descripcion: 'LOMAS DE ZAMORA' },
  { id: 138, descripcion: 'CATEDRAL' },
  { id: 139, descripcion: 'MORENO' },
  { id: 140, descripcion: 'VILLA BALLESTER' },
  { id: 141, descripcion: 'SAN PEDRO' },
  { id: 142, descripcion: 'ESTACIÓN MARTINEZ' },
  { id: 143, descripcion: 'CATAMARCA' },
  { id: 144, descripcion: 'SAN LUIS' },
  { id: 145, descripcion: 'LEANDRO N. ALEM' },
  { id: 146, descripcion: 'TIRO SUIZO' },
  { id: 147, descripcion: 'MIRAMAR' },
  { id: 148, descripcion: 'ALTA CORDOBA' },
  { id: 149, descripcion: 'BOLIVAR' },
  { id: 150, descripcion: 'CONCEP. DEL URUGUAY' },
  { id: 151, descripcion: 'AV. VELEZ SARSFIELD' },
  { id: 152, descripcion: 'LUIS GUILLON' },
  { id: 153, descripcion: 'AV. ENTRE RIOS' },
  { id: 154, descripcion: 'VILLA DEVOTO SUD' },
  { id: 155, descripcion: 'LAS FLORES' },
  { id: 156, descripcion: '9 DE JULIO' },
  { id: 157, descripcion: 'PARQUE AVELLANEDA' },
  { id: 158, descripcion: 'PATERNAL' },
  { id: 159, descripcion: 'CHACARITA' },
  { id: 160, descripcion: 'AV. CHICLANA' },
  { id: 161, descripcion: 'QUILMES OESTE' },
  { id: 162, descripcion: 'OLIVOS ALTO' },
  { id: 163, descripcion: 'V.DEVOTO NORTE' },
  { id: 164, descripcion: 'OBERA' },
  { id: 165, descripcion: 'SAN ISIDRO' },
  { id: 166, descripcion: 'AVDA.LURO - M.D.P.' },
  { id: 167, descripcion: 'CONCEPCION (TUCUMAN)' },
  { id: 168, descripcion: 'EL DORADO' },
  { id: 169, descripcion: 'CONGRESO' },
  { id: 170, descripcion: 'AV. ITALIA - RIO CUARTO' },
  { id: 171, descripcion: 'NECOCHEA' },
  { id: 172, descripcion: 'LA PLATA' },
  { id: 173, descripcion: 'SALTA' },
  { id: 174, descripcion: 'MONTE CASTRO' },
  { id: 175, descripcion: 'DIAGONAL NORTE' },
  { id: 176, descripcion: 'RIO CUARTO' },
  { id: 177, descripcion: 'LA RIOJA' },
  { id: 178, descripcion: 'COMODORO RIVADAVIA' },
  { id: 179, descripcion: 'MONTE GRANDE' },
  { id: 180, descripcion: 'ADROGUE' },
  { id: 181, descripcion: 'SAN FERNANDO' },
  { id: 182, descripcion: 'PARERA' },
  { id: 183, descripcion: 'MORON' },
  { id: 184, descripcion: 'NEUQUEN' },
  { id: 185, descripcion: 'CARREFOUR SAN JUST' },
  { id: 186, descripcion: 'PARQUE LELOIR' },
  { id: 187, descripcion: 'MONOLITO MDP' },
  { id: 188, descripcion: 'JUMBO PARQUE BROWN' },
  { id: 189, descripcion: 'VIEDMA' },
  { id: 190, descripcion: 'WILDE' },
  { id: 191, descripcion: 'JUMBO SAN MARTIN' },
  { id: 192, descripcion: 'DOBLAS Y PEDRO GOYENA' },
  { id: 193, descripcion: 'SUPER VEA GODOY CR' },
  { id: 194, descripcion: 'BARRANCAS DE BELGRANO' },
  { id: 195, descripcion: 'ROSARIO CIRCUNVAL' },
  { id: 196, descripcion: 'NUEVA CORDOBA' },
  { id: 197, descripcion: 'AV. SABATTINI' },
  { id: 198, descripcion: 'RIO GALLEGOS' },
  { id: 199, descripcion: 'CERRO DE LAS ROSAS' },
  { id: 207, descripcion: 'DEPARTAMENTALIZACION' },
  { id: 208, descripcion: 'PROCESAMIENTO Y CONTROL DE TRANSACCIONES' },
  { id: 209, descripcion: 'SAN ISIDRO' },
  { id: 210, descripcion: 'MAIPU MENDOZA' },
  { id: 211, descripcion: 'AMERICANOS NVO.CTR' },
  { id: 212, descripcion: 'JUMBO PALERMO' },
  { id: 213, descripcion: 'EL LIBERTADOR' },
  { id: 214, descripcion: 'VIAMONTE' },
  { id: 215, descripcion: 'AGOTE' },
  { id: 216, descripcion: 'DIAGONAL SUR' },
  { id: 217, descripcion: 'PARQUE INDUSTRIAL PILAR' },
  { id: 218, descripcion: 'TRIBUNALES' },
  { id: 219, descripcion: 'LOMAS DE S.ISIDRO' },
  { id: 220, descripcion: 'ROSARIO - FISHERTON' },
  { id: 221, descripcion: 'LA PLATA NORTE' },
  { id: 222, descripcion: 'MENDOZA - SAN RAFAEL' },
  { id: 223, descripcion: 'MAIPU' },
  { id: 224, descripcion: 'MENDOZA - SAN MARTIN' },
  { id: 225, descripcion: 'MENDOZA - PARQUE INDUSTRIAL' },
  { id: 226, descripcion: 'AV.SANTA FE' },
  { id: 227, descripcion: 'AV. LAS HERAS' },
  { id: 228, descripcion: 'QUILMES ALEM' },
  { id: 229, descripcion: 'PARQUE INDUSTRIAL SAN FRANCISCO' },
  { id: 230, descripcion: 'LA PLATA CALLE 12' },
  { id: 231, descripcion: 'EL ROSEDAL' },
  { id: 232, descripcion: 'SAENZ PEÑA' },
  { id: 233, descripcion: 'ROSARIO PASEO DEL SIGLO' },
  { id: 234, descripcion: 'FACULTAD DE CIENCIAS ECONOMICAS' },
  { id: 235, descripcion: 'ESCOBAR' },
  { id: 236, descripcion: 'PLAZA DE MAYO' },
  { id: 237, descripcion: 'M.PLATA.AV.CONSTI' },
  { id: 238, descripcion: 'JUMBO-QUILMES' },
  { id: 239, descripcion: 'LA ANONIMA NEUQUEN' },
  { id: 240, descripcion: 'POLO INDUSTRIAL EZEIZA' },
  { id: 241, descripcion: 'JUMBO UNICENTER' },
  { id: 242, descripcion: 'JUMBO PILAR' },
  { id: 243, descripcion: 'AV. BELGRANO' },
  { id: 244, descripcion: 'PEATONAL FLORIDA' },
  { id: 245, descripcion: 'BELGRANO R' },
  { id: 246, descripcion: 'MENDOZA - ARISTIDES VILLANUEVA' },
  { id: 247, descripcion: 'MENDOZA - GUAYMALLEN' },
  { id: 248, descripcion: 'VILLA URQUIZA' },
  { id: 249, descripcion: 'FACULTAD DE MEDIC' },
  { id: 250, descripcion: 'HURLINGHAM' },
  { id: 251, descripcion: 'SANTA ROSA' },
  { id: 253, descripcion: 'MENDOZA - LUJAN DE CUYO' },
  { id: 254, descripcion: 'GENERAL ROCA' },
  { id: 256, descripcion: 'PUERTO MADRYN' },
  { id: 257, descripcion: 'RIVADAVIA Y CARABOBO' },
  { id: 258, descripcion: 'TRELEW' },
  { id: 259, descripcion: 'SUNCHALES' },
  { id: 260, descripcion: 'ESPERANZA' },
  { id: 261, descripcion: 'BAHIA BLANCA' },
  { id: 262, descripcion: 'FRANCK' },
  { id: 263, descripcion: 'SAN CARLOS - CTRO' },
  { id: 264, descripcion: 'GALVEZ' },
  { id: 265, descripcion: 'VILLA CONSTITUCION' },
  { id: 266, descripcion: 'ROS. ARROYITO' },
  { id: 267, descripcion: 'ROSARIO - LITORAL' },
  { id: 268, descripcion: 'ROSARIO SAN MARTIN' },
  { id: 269, descripcion: 'ROS. PCIAS.UNIDAS' },
  { id: 270, descripcion: 'ROSARIO GODOY' },
  { id: 271, descripcion: 'ROS. OVIDIO LAGOS' },
  { id: 272, descripcion: 'VA. CARLOS PAZ' },
  { id: 273, descripcion: 'LAGUNA LARGA' },
  { id: 274, descripcion: 'RIO TERCERO' },
  { id: 275, descripcion: 'POZO DEL MOLLE' },
  { id: 276, descripcion: 'HERNANDO' },
  { id: 277, descripcion: 'GENERAL DEHEZA' },
  { id: 278, descripcion: 'BELL VILLE' },
  { id: 279, descripcion: 'JUSTINIANO POSSE' },
  { id: 280, descripcion: 'LEONES' },
  { id: 281, descripcion: 'MARCOS JUAREZ' },
  { id: 282, descripcion: 'MESA DE DINERO' },
  { id: 283, descripcion: 'ARMSTRONG' },
  { id: 284, descripcion: 'CORRAL DE BUSTOS' },
  { id: 285, descripcion: 'CDBA. CENTRO' },
  { id: 286, descripcion: 'CDBA. EMPALME' },
  { id: 287, descripcion: 'CDBA. SAN MARTIN' },
  { id: 288, descripcion: 'CDBA. JUAN B.JUSTO' },
  { id: 289, descripcion: 'CDBA. V.SARSFIELD' },
  { id: 290, descripcion: 'CDBA.LOS GRANADERO' },
  { id: 291, descripcion: 'CDBA. 25 DE MAYO' },
  { id: 292, descripcion: 'VA.MERCEDES S.LUIS' },
  { id: 293, descripcion: 'LABOULAYE' },
  { id: 294, descripcion: 'RUFINO' },
  { id: 295, descripcion: 'HUINCA RENANCO' },
  { id: 296, descripcion: 'GENERAL VILLEGAS' },
  { id: 297, descripcion: 'RIO IV SOBREMONTE' },
  { id: 298, descripcion: '' },
  { id: 299, descripcion: 'RIO IV SABATTINI' },
  { id: 300, descripcion: 'MENDOZA - GODOY CRUZ' },
  { id: 301, descripcion: 'MDZA.-AV.S.MARTIN' },
  { id: 302, descripcion: 'MDZA.-TUNUYAN' },
  { id: 303, descripcion: 'MEDRANO' },
  { id: 304, descripcion: 'ADROGUE OESTE' },
  { id: 305, descripcion: 'WILDE' },
  { id: 306, descripcion: 'PLAZA LAVALLE' },
  { id: 307, descripcion: 'LINCOLN' },
  { id: 308, descripcion: 'TIGRE' },
  { id: 309, descripcion: 'ACASUSSO ALTO' },
  { id: 310, descripcion: 'MENDOZA - CHACRAS DE CORIA' },
  { id: 311, descripcion: 'MZA - PASO DE LOS ANDES' },
  { id: 312, descripcion: 'MZA. - MUNICIPALIDAD' },
  { id: 313, descripcion: 'PACHECO' },
  { id: 314, descripcion: 'ESTACION AGUERO' },
  { id: 315, descripcion: 'LA PLATA - GONNET' },
  { id: 316, descripcion: 'LA PLATA - TRIBUNALES' },
  { id: 317, descripcion: 'TUCUMAN - BARRIO NORTE' },
  { id: 318, descripcion: 'SANTA FE - CASA DE GOBIERNO' },
  { id: 319, descripcion: 'ZARATE' },
  { id: 320, descripcion: 'ESTACION MALABIA' },
  { id: 321, descripcion: 'RIOBAMBA' },
  { id: 322, descripcion: 'BELGRANO' },
  { id: 323, descripcion: 'AVENIDA CABILDO' },
  { id: 324, descripcion: 'PATIO BULLRICH' },
  { id: 325, descripcion: 'CALLAO Y ARENALES' },
  { id: 326, descripcion: 'TRIBUNALES' },
  { id: 327, descripcion: 'RETIRO' },
  { id: 328, descripcion: 'BOYACA' },
  { id: 329, descripcion: 'ALTO PALERMO' },
  { id: 330, descripcion: 'LA LUCILA' },
  { id: 331, descripcion: 'LOMAS DE ZAMORA CENTRO' },
  { id: 332, descripcion: 'RAMOS MEJIA CENTRO' },
  { id: 333, descripcion: 'PALERMO NORTE' },
  { id: 334, descripcion: 'BARRIO PALERMO CHICO' },
  { id: 335, descripcion: 'GOLF SAN ISIDRO' },
  { id: 336, descripcion: 'IGLESIA DEL SOCORRO' },
  { id: 337, descripcion: 'CORDOBA PLAZA SAN MARTIN' },
  { id: 338, descripcion: 'PLAZA JURAMENTO' },
  { id: 339, descripcion: 'FLORIDA II' },
  { id: 340, descripcion: 'GUEMES' },
  { id: 341, descripcion: 'PEHUAJO' },
  { id: 342, descripcion: 'TRENQUE LAUQUEN' },
  { id: 343, descripcion: 'ZARATE' },
  { id: 344, descripcion: 'JESUS MARIA' },
  { id: 345, descripcion: 'RECONQUISTA' },
  { id: 346, descripcion: 'USHUAIA' },
  { id: 347, descripcion: 'RIO GRANDE' },
  { id: 348, descripcion: 'TRELEW' },
  { id: 349, descripcion: 'CIPOLLETTI' },
  { id: 350, descripcion: 'CANNING' },
  { id: 351, descripcion: 'COMODORO RIVADAVIA - BARRIO INDUSTRIAL' },
  { id: 352, descripcion: 'VILLA MERCEDES' },
  { id: 353, descripcion: 'BICENTENARIO' },
  { id: 354, descripcion: 'AVENIDA VICTORICA' },
  { id: 355, descripcion: 'RECTA MARTINOLLI' },
  { id: 356, descripcion: 'DISTRITO GALICIA' },
  { id: 357, descripcion: 'TUCUMÁN - BARRIO NORTE' },
  { id: 358, descripcion: 'PUERTO MADERO' },
  { id: 359, descripcion: 'SAN LORENZO' },
  { id: 360, descripcion: 'AV. ALVEAR' },
  { id: 361, descripcion: 'TORTUGAS MALL' },
  { id: 362, descripcion: 'BOULEVARD SAN JUAN' },
  { id: 363, descripcion: 'VILLA URQUIZA' },
  { id: 364, descripcion: 'SALADILLO' },
  { id: 365, descripcion: 'PASEO DEL ANGEL' },
  { id: 366, descripcion: 'ESTACIÓN PASTEUR' },
  { id: 367, descripcion: 'PALMAS DEL PILAR' },
  { id: 368, descripcion: 'PINAMAR' },
  { id: 369, descripcion: 'BALCARCE' },
  { id: 370, descripcion: 'MALABIA' },
  { id: 371, descripcion: 'BERAZATEGUI' },
  { id: 372, descripcion: 'VILLA ADELINA' },
  { id: 373, descripcion: 'LA PLATA - AVENIDA 44' },
  { id: 374, descripcion: 'YERBA BUENA' },
  { id: 375, descripcion: 'ESQUEL' },
  { id: 376, descripcion: 'CITY BELL' },
  { id: 377, descripcion: 'CORONEL SUAREZ' },
  { id: 378, descripcion: 'PARQUE RIVADAVIA' },
  { id: 379, descripcion: 'SAN PEDRO' },
  { id: 380, descripcion: 'BOULEVARD GALVEZ' },
  { id: 381, descripcion: 'MICROCENTRO RECONQUISTA' },
  { id: 382, descripcion: 'MICROCENTRO CARLOS PELLEGRINI' },
  { id: 383, descripcion: 'NORDELTA' },
  { id: 384, descripcion: 'MALVINAS' },
  { id: 385, descripcion: 'Estacion Villa del Parque' },
  { id: 386, descripcion: 'CUTRAL CO' },
  { id: 387, descripcion: 'FICTICIA-TRANSM.CAJERO AUTOMATICO' },
  { id: 388, descripcion: 'TARJETAS PRIVADAS (LEGALES)' },
  { id: 389, descripcion: 'ATENCION DPBS CASA MATRIZ' },
  { id: 390, descripcion: 'AÑELO' },
  { id: 391, descripcion: 'CAÑUELAS' },
  { id: 392, descripcion: 'BURZACO' },
  { id: 393, descripcion: 'PARQUE PATRICIOS' },
  { id: 394, descripcion: 'LAGUNA DEL SOL' },
  { id: 395, descripcion: 'ENSENADA' },
  { id: 396, descripcion: 'SAN JUSTO UNIVERSIDAD' },
  { id: 397, descripcion: 'TUCUMAN TRIBUNALES' },
  { id: 398, descripcion: 'EL TALAR' },
  { id: 399, descripcion: 'VILLA GOB. GALVEZ' },
  { id: 400, descripcion: 'PLAZA GALICIA' },
  { id: 401, descripcion: 'ANEXO CINCO ESQUINAS' },
  { id: 402, descripcion: 'U. OPERATIVA CORDOBA' },
  { id: 403, descripcion: 'U. OPERATIVA MAR DEL PLATA' },
  { id: 404, descripcion: 'U. OPERATIVA ROSARIO' },
  { id: 405, descripcion: 'U. OPERATIVA RECOLETA' },
  { id: 406, descripcion: 'UNIDAD OPERATIVA SALTA' },
  { id: 407, descripcion: 'UNIDAD OPERATIVA CENTRO' },
  { id: 408, descripcion: 'UNIDAD ADMIN. CENTRALIZADA - VENDIMIA' },
  { id: 409, descripcion: 'UNIDAD COMERCIAL CENTRALIZADA' },
  { id: 410, descripcion: 'UNIDAD ADMINST. CENTRAL(UAC)' },
  { id: 411, descripcion: 'GERENCIA REGIONAL CORDOBA' },
  { id: 412, descripcion: 'GERENCIA REGIONAL ROSARIO' },
  { id: 414, descripcion: 'CENTRO PAGO A PROVEEDORES' },
  { id: 430, descripcion: 'EASY HOMECENTER' },
  { id: 431, descripcion: 'UAC' },
  { id: 432, descripcion: 'AV. CONSTITUCION' },
  { id: 433, descripcion: 'TOLEDO MAR DEL PLATA' },
  { id: 434, descripcion: 'TOLEDO CONSTITUCION' },
  { id: 436, descripcion: 'EKONO JUAN B. JUSTO' },
  { id: 437, descripcion: 'EKONO VILLA URQUIZA' },
  { id: 438, descripcion: 'EKONO LANUS' },
  { id: 440, descripcion: 'VEA GODOY CRUZ' },
  { id: 441, descripcion: 'VEA SAN RAFAEL' },
  { id: 442, descripcion: 'VEA SAN JUAN' },
  { id: 443, descripcion: 'AMERICANO CORDOBA' },
  { id: 444, descripcion: 'TARJETAS MOROSAS' },
  { id: 445, descripcion: 'SPAR VILLA ALLENDE' },
  { id: 446, descripcion: 'EKONO ACOYTE' },
  { id: 448, descripcion: 'EKONO SAN JUAN' },
  { id: 449, descripcion: 'EASY QUILMES' },
  { id: 450, descripcion: 'LOCAL RAMOS MEJIA' },
  { id: 451, descripcion: 'EKONO GRAL PACHECO' },
  { id: 452, descripcion: 'LA ANON.9 DE JULIO' },
  { id: 453, descripcion: 'BANKING AMERICANO AV.COLON' },
  { id: 454, descripcion: 'PASEO DIAGONAL MAR DEL PLATA' },
  { id: 455, descripcion: 'SAN MIGUEL CENTRO' },
  { id: 500, descripcion: 'BANKING CENTER-DEMO' },
  { id: 501, descripcion: 'GA ONCE' },
  { id: 502, descripcion: 'GA PLAZA ITALA' },
  { id: 503, descripcion: 'GA AVELLANEDA' },
  { id: 504, descripcion: 'GA LOMAS DE ZAMORA' },
  { id: 505, descripcion: 'GA MUNRO' },
  { id: 506, descripcion: 'GA SAN MARTIN' },
  { id: 507, descripcion: 'GA SAN ISIDRO' },
  { id: 508, descripcion: 'GA SAN JUSTO' },
  { id: 509, descripcion: 'GA JOSE C PAZ' },
  { id: 510, descripcion: 'GA BANFIELD' },
  { id: 511, descripcion: 'GA ABASTO' },
  { id: 512, descripcion: 'GA MORON' },
  { id: 513, descripcion: 'GA SARANDI' },
  { id: 514, descripcion: 'GA MERLO' },
  { id: 515, descripcion: 'GA CASA CENTRAL' },
  { id: 516, descripcion: 'GA BERAZATEGUI' },
  { id: 517, descripcion: 'GA BARRIO NORTE' },
  { id: 518, descripcion: 'GA SAN MIGUEL' },
  { id: 519, descripcion: 'GA FLORES' },
  { id: 520, descripcion: 'GA MARTINEZ' },
  { id: 521, descripcion: 'GA CHACARITA' },
  { id: 522, descripcion: 'GA PZA. SAN MARTIN' },
  { id: 523, descripcion: 'GA PLAZA LAS HERAS' },
  { id: 524, descripcion: 'GA FLORENCIO VAREL' },
  { id: 525, descripcion: 'GA MONTE GRANDE' },
  { id: 526, descripcion: 'GA CONGRESO' },
  { id: 527, descripcion: 'GA VILLA CRESPO' },
  { id: 528, descripcion: 'GA NUEVA POMPEYA' },
  { id: 529, descripcion: 'GA LANUS' },
  { id: 530, descripcion: 'GA PQUE CENTENARIO' },
  { id: 531, descripcion: 'ALMAGRO' },
  { id: 532, descripcion: 'FLORESTA' },
  { id: 533, descripcion: 'WILDE' },
  { id: 534, descripcion: 'GA LA BOCA' },
  { id: 535, descripcion: 'GA VILLA URQUIZA' },
  { id: 536, descripcion: 'GA BERNAL' },
  { id: 537, descripcion: 'GA RAMOS MEJIA' },
  { id: 538, descripcion: 'GA MORENO' },
  { id: 539, descripcion: 'GA LOS POLVORINES' },
  { id: 540, descripcion: 'GA LOM.DEL MIRADOR' },
  { id: 541, descripcion: 'GA RAFAEL CASTILLO' },
  { id: 542, descripcion: 'GA  I.CASANOVA' },
  { id: 543, descripcion: 'GA TIGRE' },
  { id: 544, descripcion: 'GA VILLA MARTELLI' },
  { id: 545, descripcion: 'GA CASEROS' },
  { id: 546, descripcion: 'GA SAN CRISTOBAL' },
  { id: 547, descripcion: 'GA QUILMES ALVEAR' },
  { id: 548, descripcion: 'GA VILLA LINCH' },
  { id: 549, descripcion: 'GA LINIERS' },
  { id: 550, descripcion: 'GA ITUZAINGO' },
  { id: 551, descripcion: 'GA VILLA DEL PARQ' },
  { id: 552, descripcion: 'GA S.FRANCISCO SO' },
  { id: 553, descripcion: 'GA MONTE CASTRO' },
  { id: 554, descripcion: 'GA TEMPERLEY' },
  { id: 555, descripcion: 'DPTO. TARJETAS' },
  { id: 556, descripcion: 'GA LLAVALLOL' },
  { id: 557, descripcion: 'GA QUILMES OESTE' },
  { id: 558, descripcion: 'GA BARRACAS' },
  { id: 559, descripcion: 'GA CASEROS Y E.RIO' },
  { id: 560, descripcion: 'GA MATADEROS' },
  { id: 561, descripcion: 'GA BURZACO' },
  { id: 562, descripcion: 'GA SAN JUAN/SAN JO' },
  { id: 563, descripcion: 'GA CRUCE VARELA' },
  { id: 564, descripcion: 'GA AV.MAYO' },
  { id: 565, descripcion: 'GA LONGCHAMPS' },
  { id: 566, descripcion: 'GA GERLI' },
  { id: 567, descripcion: 'GA VALENTIN ALSINA' },
  { id: 568, descripcion: 'GA BARRIO SAN JOSE' },
  { id: 569, descripcion: 'GA LAFERRERE' },
  { id: 570, descripcion: 'GA V.LOMA HERMOSA' },
  { id: 571, descripcion: 'GA NUÑEZ' },
  { id: 572, descripcion: 'GA CORDOBA Y FLORIDA' },
  { id: 573, descripcion: 'GA SAN FERNANDO' },
  { id: 574, descripcion: 'GA PARQUE PATRICIOS' },
  { id: 575, descripcion: 'GA GRAL. RODRIGUEZ' },
  { id: 576, descripcion: 'GA LUJAN' },
  { id: 577, descripcion: 'GA BELGRANO' },
  { id: 578, descripcion: 'GA VILLA BALLESTER' },
  { id: 579, descripcion: 'GA JOSE LEON SUAREZ' },
  { id: 580, descripcion: 'GA PARQUE CHACABUCO' },
  { id: 581, descripcion: 'GA LA PLATA' },
  { id: 582, descripcion: 'GA SAN VICENTE' },
  { id: 583, descripcion: 'GA LOBOS' },
  { id: 584, descripcion: 'GA CHASCOMUS' },
  { id: 585, descripcion: 'GA CORONEL BRANDSEN' },
  { id: 586, descripcion: 'GA CAMPANA' },
  { id: 587, descripcion: 'GA ZARATE' },
  { id: 588, descripcion: 'GA SAN PEDRO' },
  { id: 589, descripcion: 'GA SAN NICOLAS' },
  { id: 590, descripcion: 'GA MERCEDES' },
  { id: 591, descripcion: 'GA CHIVILCOY' },
  { id: 592, descripcion: 'GA BRAGADO' },
  { id: 593, descripcion: 'GA 9 DE JULIO' },
  { id: 594, descripcion: 'GA PEHUAJO' },
  { id: 595, descripcion: 'GA TRENQUE LAUQUEN' },
  { id: 596, descripcion: 'GA BOLIVAR' },
  { id: 597, descripcion: 'GA ESCOBAR' },
  { id: 598, descripcion: 'GA DON TORCUATO' },
  { id: 599, descripcion: 'GA CAÑUELAS' },
  { id: 600, descripcion: 'GA MAR DEL PLATA-CENTRO' },
  { id: 601, descripcion: 'GA PERGAMINO' },
  { id: 602, descripcion: 'GA SALTO' },
  { id: 603, descripcion: 'GA ROJAS' },
  { id: 604, descripcion: 'GA JUNIN' },
  { id: 605, descripcion: 'GA LINCOLN' },
  { id: 606, descripcion: 'GA LOS TOLDOS' },
  { id: 607, descripcion: 'GA CHACABUCO' },
  { id: 608, descripcion: 'GA SAN MIGUEL DEL MONTE' },
  { id: 609, descripcion: 'GA LAS FLORES' },
  { id: 610, descripcion: 'GA AZUL' },
  { id: 611, descripcion: 'GA OLAVARRIA' },
  { id: 612, descripcion: 'GA MAR DEL PLATA-PUERTO' },
  { id: 613, descripcion: 'GA MAR DEL PLATA-EL PROGRESO' },
  { id: 614, descripcion: 'GA TANDIL' },
  { id: 615, descripcion: 'GA TRES ARROYOS' },
  { id: 616, descripcion: 'GA CORDOBA - CENTRAL' },
  { id: 617, descripcion: 'GA CORDOBA - BARRIO SAN VICENTE' },
  { id: 618, descripcion: 'GA BENITO JUAREZ' },
  { id: 619, descripcion: 'GA NECOCHEA' },
  { id: 620, descripcion: 'GA DOLORES' },
  { id: 621, descripcion: 'GA CORONEL DORREGO' },
  { id: 622, descripcion: 'GA BALCARCE' },
  { id: 623, descripcion: 'GA GONZALEZ CHAVEZ' },
  { id: 624, descripcion: 'GA CORONEL SUAREZ' },
  { id: 625, descripcion: 'GA GUALEGUAYCHU' },
  { id: 626, descripcion: 'GA BARADERO' },
  { id: 627, descripcion: 'GA MAIPU' },
  { id: 628, descripcion: 'GA MIRAMAR' },
  { id: 629, descripcion: 'GA FORMOSA' },
  { id: 630, descripcion: 'GA RESISTENCIA' },
  { id: 631, descripcion: 'GA CORRIENTES' },
  { id: 632, descripcion: 'GA POSADAS' },
  { id: 633, descripcion: 'GA OLIVOS' },
  { id: 634, descripcion: 'GA TRIBUNALES I' },
  { id: 635, descripcion: 'GA VILLA LUGANO' },
  { id: 636, descripcion: 'GA LA PLATA II' },
  { id: 637, descripcion: 'GA CORDOBA RIO IV' },
  { id: 638, descripcion: 'GA CORDOBA - VILLA MARIA' },
  { id: 639, descripcion: 'GA MONSERRAT' },
  { id: 640, descripcion: 'GA BAHIA BLANCA' },
  { id: 641, descripcion: 'GA BAHIA BLANCA - VILLA MITRE' },
  { id: 642, descripcion: 'GA ROSARIO - CENTRAL' },
  { id: 643, descripcion: 'GA ROSARIO - PARAGUAY' },
  { id: 644, descripcion: 'GA SANTA FE - CENTRAL' },
  { id: 645, descripcion: 'GA SANTA FE-PEATONAL' },
  { id: 646, descripcion: 'GA PARANA' },
  { id: 647, descripcion: 'GA CONCORDIA' },
  { id: 648, descripcion: 'GA ROSARIO - ALBERDI' },
  { id: 649, descripcion: 'GA SAN LUIS - CENTRAL' },
  { id: 650, descripcion: 'GA MENDOZA - CENTRAL' },
  { id: 651, descripcion: 'GA SAN JUAN - CENTRAL' },
  { id: 652, descripcion: 'GA MENDOZA - GENERAL PAZ' },
  { id: 653, descripcion: 'GA GODOY CRUZ' },
  { id: 654, descripcion: 'GA LUJAN DE CUYO' },
  { id: 655, descripcion: 'GA SAN RAFAEL' },
  { id: 656, descripcion: 'GA VILLA MERCEDES' },
  { id: 657, descripcion: 'GA - PILAR' },
  { id: 666, descripcion: 'PERSONAL SUPERIOR DE BANELCO' },
  { id: 682, descripcion: 'T. DE CREDITO - SUC 82 -BCO DORREGO' },
  { id: 700, descripcion: 'AV. HIPOLITO IRIGOYEN' },
  { id: 701, descripcion: 'HONDURAS' },
  { id: 702, descripcion: 'ESTACION RAMALLO' },
  { id: 703, descripcion: 'SHOPPING DOT' },
  { id: 704, descripcion: 'BOULEVARD ALBERDI' },
  { id: 777, descripcion: 'TARJETA DE CREDITO VISA' },
  { id: 802, descripcion: 'Minibanco Coca Cola' },
  { id: 832, descripcion: 'CODIGO DE DESCUENTO - CORDOBA' },
  { id: 888, descripcion: 'DPTO. TARJETAS' },
  { id: 942, descripcion: 'MUNICIPALIDAD DE CORDOBA' },
  { id: 962, descripcion: 'RECURSOS HUMANOS' },
  { id: 970, descripcion: 'GRABOSCH' },
  { id: 980, descripcion: 'PROM. Y VENTAS' },
  { id: 990, descripcion: 'TORRE' },
  { id: 991, descripcion: 'TESORO 991' },
  { id: 998, descripcion: 'POR SISTEMA' },
  { id: 999, descripcion: 'SUCURSAL CASA MATRIZ' },
  { id: 1001, descripcion: 'DIRECTORIO' },
  { id: 1002, descripcion: 'GERENCIA GENERAL' },
  { id: 1003, descripcion: 'COMITE DE AUDITORIA' },
  { id: 1004, descripcion: 'SECRETARIA DE DIRECTORIO' },
  { id: 1005, descripcion: 'UNIDAD ANTI LAVADO' },
  { id: 1006, descripcion: 'RIESGOS' },
  { id: 1007, descripcion: 'ANALISIS Y PLANEAMIENTO NEG. MAYORISTAS' },
  { id: 1008, descripcion: 'DESARROLLO NEGOCIOS CORPORATIVOS' },
  { id: 1009, descripcion: 'PRIVATE EQUITY' },
  { id: 1010, descripcion: 'CREDITOS' },
  { id: 1011, descripcion: 'PROYECTOS ESPECIALES' },
  { id: 1012, descripcion: 'DPTO. DE CREDITOS - PYME' },
  { id: 1013, descripcion: 'DPTO. DE CREDITOS - AGROPECUARIO' },
  { id: 1014, descripcion: 'PRESTAMOS Y PROYECTOS DE INVERSION' },
  { id: 1015, descripcion: 'DPTO. DE CREDITOS - GARANTIAS' },
  { id: 1016, descripcion: 'DPTO. DE CREDITOS' },
  { id: 1017, descripcion: 'DPTO. DE CRED.-DEUDORES. SIT. IRREGULAR' },
  { id: 1018, descripcion: 'RELACIONES TECNICAS' },
  { id: 1019, descripcion: 'DPTO. OPERATIVO DE CREDITO - DESCUENTOS' },
  { id: 1020, descripcion: 'GESTIÓN CRÉDITOS ESPECIALES Y JUDICIAL' },
  { id: 1021, descripcion: 'GESTIÓN DE CLIENTES EN MORA MINORISTA' },
  { id: 1022, descripcion: 'GESTIÓN JUDICIAL' },
  { id: 1023, descripcion: 'CRÉDITO MAYORISTA - ZONA 1' },
  { id: 1024, descripcion: 'SUPERVISION BANCOS, SECTOR PUBLICO E INT' },
  { id: 1025, descripcion: 'PUBLICIDAD, PROMOCION E IMAGEN' },
  { id: 1026, descripcion: 'SUPERVISIÓN DE EMPRESAS CORDOBA' },
  { id: 1027, descripcion: 'E-GALICIA- DESARROLLO COMERCIAL' },
  { id: 1028, descripcion: 'Centro de costo 1028' },
  { id: 1029, descripcion: 'E-GALICIA MOVIL' },
  { id: 1030, descripcion: 'BANCA CORPORATIVA' },
  { id: 1031, descripcion: 'PRODUCTOS Y MARKETING MAYORISTA' },
  { id: 1032, descripcion: 'CORPORATIVAS' },
  { id: 1033, descripcion: 'GRANDES EMPRESAS TEAM 2' },
  { id: 1034, descripcion: 'GRANDES EMPRESAS SUBGERENTE' },
  { id: 1035, descripcion: 'MEDIANAS EMPRESAS' },
  { id: 1036, descripcion: 'MEDIANAS EMPRESAS-REGION METRO 1' },
  { id: 1037, descripcion: 'MEDIANAS EMPRESAS-REGION METRO 2' },
  { id: 1038, descripcion: 'MEDIANAS EMPRESAS-REGION INTERIOR' },
  { id: 1039, descripcion: 'MEDIANAS EMPRESAS-REGIONES' },
  { id: 1040, descripcion: 'DPTO. NEGOCIOS INMOBILIARIOS' },
  { id: 1041, descripcion: 'MEDIANAS EMPRESAS-CONSTRUCCION E INMOBIL' },
  { id: 1042, descripcion: 'GESTION COMERCIAL Y SOPORTE' },
  { id: 1043, descripcion: 'OP.CENTRALIZADAS HIPOTECARIOS INDIVIDUOS' },
  { id: 1044, descripcion: 'AUDITORIA JURIDICA' },
  { id: 1045, descripcion: 'GESTIÓN DE CRÉDITOS EXTRAJUDICIAL' },
  { id: 1046, descripcion: 'FIDEICOMISO COMERCIAL PRENDARIO' },
  { id: 1047, descripcion: 'ANÁLISIS Y PREVENCIÓN DEL FRAUDE' },
  { id: 1048, descripcion: 'FIDEICOMISO COMERCIAL LEASING' },
  { id: 1049, descripcion: 'FIDEICOMISO PROSION HIPOTECAS RURALES I' },
  { id: 1050, descripcion: 'GERENCIA BANCA PRIVADA Y ADM. PATRINOMIO' },
  { id: 1051, descripcion: 'ADMINISTRACION DE PATRIMONIOS' },
  { id: 1052, descripcion: 'DPTO. SUCURSALES - FILIAL CASA MATRIZ' },
  { id: 1053, descripcion: 'S. COMERCIAL SUC. CASA MATRIZ' },
  { id: 1054, descripcion: 'SECTOR ATENCION AL PUBLICO' },
  { id: 1055, descripcion: 'SECTOR CAJA' },
  { id: 1056, descripcion: 'S. OPERATIVO SUC. CASA MATRIZ' },
  { id: 1057, descripcion: 'GESTION DE ACTIVOS - AREA METROPOLITANA' },
  { id: 1058, descripcion: 'GESTION DE ACTIVOS - AREA INTERIOR' },
  { id: 1059, descripcion: 'BANCA PRIVADA - SOP. Y GEST. COMERCIAL' },
  { id: 1060, descripcion: 'GERENCIA DTO. BANCA PRIVADA' },
  { id: 1061, descripcion: 'GALICIA PRIVATE BANKING - GERENCIA' },
  { id: 1062, descripcion: 'GALICIA PRIVATE BANKING - MATRIZ' },
  { id: 1065, descripcion: 'GAL. BANCA PRIVADA - CENTRO FLORIDA II' },
  { id: 1066, descripcion: 'GALICIA INVERSIONES - MATRIZ' },
  { id: 1067, descripcion: 'GAL. BANCA PRIVADA - CENTRO BARRIO NORTE' },
  { id: 1068, descripcion: 'GAL BANCA PRIVADA - CENTRO MAR DEL PLATA' },
  { id: 1069, descripcion: 'CENTRO REGIONAL MENDOZA' },
  { id: 1070, descripcion: 'CENTRO REGIONAL ROSARIO' },
  { id: 1071, descripcion: 'GAL. BANCA PRIVADA - CENTRO MEDITERRANEA' },
  { id: 1072, descripcion: 'CENTRO REGIONAL SAN ISIDRO' },
  { id: 1073, descripcion: 'GALICIA INVERSIONES' },
  { id: 1074, descripcion: 'GALICIA BANCA PRIVADA - CENTRO NEUQUÉN' },
  { id: 1075, descripcion: 'SISTEMAS DTO. BANCA PRIVADA' },
  { id: 1076, descripcion: 'GALICIA BANCA PRIVADA - CENTRO LA PLATA' },
  { id: 1077, descripcion: 'GALICIA BCA PRIVADA - CENTRO PCIA.BS.AS.' },
  { id: 1078, descripcion: 'CAJEROS AUTOMATICOS' },
  { id: 1079, descripcion: 'GERENCIA INTERNACIONAL' },
  { id: 1080, descripcion: 'INSTITUCIONES FINANCIERAS' },
  { id: 1081, descripcion: 'REPRESENTACION NEW YORK' },
  { id: 1082, descripcion: 'REPRESENTACION SAN PABLO' },
  { id: 1083, descripcion: 'DEPTO. RED EXTERIOR' },
  { id: 1084, descripcion: 'OTRAS SOCIEDADES VINCULADAS' },
  { id: 1085, descripcion: 'DPTO. PRODUCCION DE SEGUROS' },
  { id: 1086, descripcion: 'BANKING CENTRE' },
  { id: 1087, descripcion: 'DPTO.PROM. Y VTAS-CAJEROS AUTOMATICOS' },
  { id: 1088, descripcion: 'CONTABILIDAD Y CONCILIACIONES' },
  { id: 1089, descripcion: 'NEGOCIOS MINORISTAS' },
  { id: 1090, descripcion: 'RELACIONES INSTITUCIONALES' },
  { id: 1091, descripcion: 'HUB DE CRÉDITOS' },
  { id: 1092, descripcion: 'CONTROL MOROSIDAD' },
  { id: 1093, descripcion: 'PROYECTOS' },
  { id: 1094, descripcion: 'TARJETAS REGIONALES' },
  { id: 1095, descripcion: 'INSTRUMENTACIÓN EMPRESAS' },
  { id: 1096, descripcion: 'OPERACIONES CENTRALIZADAS' },
  { id: 1097, descripcion: 'OPERACIONES' },
  { id: 1098, descripcion: 'CUSTOMER SERVICES' },
  { id: 1099, descripcion: 'PRODUCTOS' },
  { id: 1100, descripcion: 'DPTO. MARKETING MINORISTA' },
  { id: 1101, descripcion: 'MEDIOS DE AUTOGESTIÓN' },
  { id: 1102, descripcion: 'CALIDAD' },
  { id: 1103, descripcion: 'DPTO. PRESUPUESTACION Y CONTROL' },
  { id: 1104, descripcion: 'CANALES ALTERNATIVOS' },
  { id: 1105, descripcion: 'VENTAS ESPECIALES' },
  { id: 1106, descripcion: 'VENTAS' },
  { id: 1107, descripcion: 'SAE EQUIPO CORPORATIVAS' },
  { id: 1108, descripcion: 'SAE EQUIPO PYME/AGRO + CBE' },
  { id: 1109, descripcion: 'GCIA. DE DESARROLLO COMERCIAL' },
  { id: 1110, descripcion: 'OTORGAMIENTO PYME' },
  { id: 1111, descripcion: 'CUSTOMER SERVICE' },
  { id: 1112, descripcion: 'BANCA AUTOMATICA' },
  { id: 1113, descripcion: 'REDES Y MANTENIMIENTO' },
  { id: 1114, descripcion: 'VENTAS PRODUCTOS MINORISTAS' },
  { id: 1115, descripcion: 'GERENCIA DIVISION MINORISTA' },
  { id: 1116, descripcion: 'BANCA UNIVERSITARIA' },
  { id: 1117, descripcion: 'CRÉDITOS PRENDARIOS (SIN DOTACI?N)' },
  { id: 1118, descripcion: 'DPTO NUEVOS NEGOCIOS' },
  { id: 1119, descripcion: 'FONDOS DE PENSION' },
  { id: 1120, descripcion: 'OPERACIONES COMERCIO EXTERIOR' },
  { id: 1121, descripcion: 'IMPORTACION' },
  { id: 1122, descripcion: 'ADMINISTR. DE SISTEMAS Y APOYOS' },
  { id: 1123, descripcion: 'CREDITO MAYORISTA - ADM. OPE. URUGUAY' },
  { id: 1124, descripcion: 'PROCRED - CABA' },
  { id: 1125, descripcion: 'COBROS Y PAGOS' },
  { id: 1126, descripcion: 'SOPORTE AL NEGOCIO' },
  { id: 1127, descripcion: 'COMERCIO EXTERIOR' },
  { id: 1128, descripcion: 'FACTORING' },
  { id: 1129, descripcion: 'FINANCIACIONES' },
  { id: 1130, descripcion: 'CENTRO DE CONTACTOS CON CLIENTES' },
  { id: 1131, descripcion: 'TELEMARKETING' },
  { id: 1132, descripcion: 'MUTUALES - CODIGO DE DESCUENTO CORDOBA' },
  { id: 1133, descripcion: 'SUDECOR RESIDUAL' },
  { id: 1134, descripcion: 'CENTRO DE INVERSIONES' },
  { id: 1135, descripcion: 'RECUPERO DE LA MORA' },
  { id: 1136, descripcion: 'SOPORTE AL NEGOCIO Y MEJORA CONTINUA' },
  { id: 1137, descripcion: 'DISTRIBUCION DE GALICIA AHORA' },
  { id: 1138, descripcion: 'VTA. MINORISTA - REGION INTERIOR MDP SUR' },
  { id: 1139, descripcion: 'CANAL INMOBILIARIO' },
  { id: 1140, descripcion: 'CONTADURIA' },
  { id: 1141, descripcion: 'DATA WAREHOUSE' },
  { id: 1142, descripcion: 'ADMINISTRACIONES FIDUCIARIAS Y NEG. COMP' },
  { id: 1143, descripcion: 'PUNTO DE VENTA' },
  { id: 1144, descripcion: 'PASIVOS Y TRADING' },
  { id: 1145, descripcion: 'SOLUCIONES COBROS Y PAGOS' },
  { id: 1146, descripcion: 'PLATAFORMA DIGITAL EMPRESAS' },
  { id: 1147, descripcion: 'VENTA MINORISTA - REGION CORDOBA' },
  { id: 1148, descripcion: 'VENTA MINORISTA - REGION MENDOZA' },
  { id: 1149, descripcion: 'VENTA MINORISTA - REGION ROSARIO' },
  { id: 1150, descripcion: 'OPERACIONES' },
  { id: 1151, descripcion: 'SERVICIOS A EMPRESAS' },
  { id: 1152, descripcion: 'DPTO. OPERACIONES-DATA ENTRY' },
  { id: 1153, descripcion: 'PROCESAMIENTO DE CHEQUES' },
  { id: 1154, descripcion: 'ATMS MOVILES' },
  { id: 1155, descripcion: 'CONMUTADOR' },
  { id: 1156, descripcion: 'OPERACIONES DE SEGUROS' },
  { id: 1157, descripcion: 'CENTRO DE ATENCIÃ“N DIGITAL' },
  { id: 1158, descripcion: 'DPTO. OPERACIONES-CORRESPONDENCIA' },
  { id: 1159, descripcion: 'DPTO. OPERACIONES-COMUNICACIONES' },
  { id: 1160, descripcion: 'ADMINISTRACION DE BASE DE CLIENTES' },
  { id: 1161, descripcion: 'GAL. BANCA PRIVADA - ÁREA COMERCIAL' },
  { id: 1162, descripcion: 'SERVICIOS CENTRALIZADOS' },
  { id: 1163, descripcion: 'OPERACIONES COMPENSACION BANELCO' },
  { id: 1164, descripcion: 'DPTO. ORGANIZACION - AT. CONS. FILIALES' },
  { id: 1165, descripcion: 'SERVICIOS A TERCEROS' },
  { id: 1166, descripcion: 'ARCHIVO BELL VILLE' },
  { id: 1167, descripcion: 'DEPOSITO BOEDO' },
  { id: 1168, descripcion: 'DEPOSITO ELEMENTOS DE SEGURIDAD' },
  { id: 1169, descripcion: 'DEPOSITO ANEXO' },
  { id: 1170, descripcion: 'DISTRIBUCION Y GUARDA DE DOCUMENTACION' },
  { id: 1171, descripcion: 'ADMINISTRACION DE BIENES E INMUEBLES' },
  { id: 1172, descripcion: 'ACTIVOS FIJOS' },
  { id: 1173, descripcion: 'DTO. COMPRAS Y CONTRATACIONES' },
  { id: 1174, descripcion: 'INTENDENCIA' },
  { id: 1175, descripcion: 'LIBRERIA' },
  { id: 1176, descripcion: 'ARCHIVO' },
  { id: 1177, descripcion: 'DEPOSITO J. L. SUAREZ' },
  { id: 1178, descripcion: 'AUTOMOTORES' },
  { id: 1179, descripcion: 'CONTROL DE GESTIÓN Y DESEMPEÑO' },
  { id: 1180, descripcion: 'DPTO. SUCURSALES' },
  { id: 1181, descripcion: 'DPTO. SUCURSALES - OPERACIONES' },
  { id: 1182, descripcion: 'DPTO. SUCURSALES - PROMOCION' },
  { id: 1183, descripcion: 'GCIA. ZONAL IV' },
  { id: 1184, descripcion: 'NEGOCIOS INMOBILIARIOS Y CORPORATIVOS' },
  { id: 1185, descripcion: 'SINDICACIONES' },
  { id: 1186, descripcion: 'DPTO. SUCURSALES - ZONA III' },
  { id: 1187, descripcion: 'NEG. FIDUCIARIOS Y MERCADO DE CAPITALES' },
  { id: 1188, descripcion: 'SUCURSALES NO TRADICIONALES' },
  { id: 1189, descripcion: 'DESARROLLO DEL CANAL' },
  { id: 1190, descripcion: 'BANCA MINORISTA' },
  { id: 1191, descripcion: 'TRIBU SEGMENTO RETAIL' },
  { id: 1192, descripcion: 'GERENCIA SUCURSALES' },
  { id: 1193, descripcion: 'REGION INTERIOR 3' },
  { id: 1194, descripcion: 'OPERATORIA TBNA' },
  { id: 1195, descripcion: 'OP.CENTRALIZADAS CONSUMO INDIVIDUOS' },
  { id: 1196, descripcion: 'PMOS.CLIENTES HP OPERATORIA CENTRALIZADA' },
  { id: 1197, descripcion: 'SERVICIOS CORPORATIVOS INTEGRADOS' },
  { id: 1198, descripcion: 'CRED.MAY.-ADMIN.CARTERA DSI CON CONVENIO' },
  { id: 1199, descripcion: 'PRODUCTOS ELECTRÓNICOS' },
  { id: 1200, descripcion: 'CANAL GALICIA AHORA' },
  { id: 1201, descripcion: 'VENTA GALICIA AHORA' },
  { id: 1202, descripcion: 'OPERACIONES GALICIA AHORA' },
  { id: 1203, descripcion: 'MARKETING GALICIA AHORA' },
  { id: 1204, descripcion: 'RENTA ALTA / PRIVATE' },
  { id: 1205, descripcion: 'DTO. SEGUROS' },
  { id: 1206, descripcion: 'LICITACION BANCO CORDOBA' },
  { id: 1207, descripcion: 'CRED.MAY.-ADM.CARTERA CTES DE EMPRESAS' },
  { id: 1208, descripcion: 'CRED.MAY.-ADMIN.CARTERA OP.REF. EMPRESAS' },
  { id: 1209, descripcion: 'CRED.MAY.-ADMIN.CARTERA OP.REF. INDIVIDU' },
  { id: 1210, descripcion: 'SEGURIDAD CORPORATIVA' },
  { id: 1211, descripcion: 'SUCURSAL NUEVA YORK' },
  { id: 1212, descripcion: 'PRODUCTOS DOCUMENTARIOS' },
  { id: 1213, descripcion: 'GESTION PROGRAMAS CORPORATIVOS' },
  { id: 1214, descripcion: 'RIESGO , CTROL. Y PREV. LAVADO DE DINERO' },
  { id: 1215, descripcion: 'SUSTENTABILIDAD' },
  { id: 1216, descripcion: 'PROGRAMAS CORPORATIVOS' },
  { id: 1217, descripcion: 'GAL-SEV' },
  { id: 1218, descripcion: 'FONOCAM' },
  { id: 1219, descripcion: 'FIDEICOMISO DEUDORES EN SITUACIÓN IRREG.' },
  { id: 1220, descripcion: 'ADMINISTRACIÓN' },
  { id: 1221, descripcion: 'SOPORTE E INFORMES DE GESTIÓN' },
  { id: 1222, descripcion: 'PROCESAMIENTO PREVENTIVO Y REMEDIACIÓN' },
  { id: 1223, descripcion: 'CENTRO DE ANTENCIÓN A EMPRESAS' },
  { id: 1224, descripcion: 'CANAL OPERATIVO Y LOG. DE DOCUMENTACION' },
  { id: 1225, descripcion: 'PAGO A PROVEEDORES DE CLIENTES' },
  { id: 1226, descripcion: 'ATENCIÓN TELEFÓNICA COMEX' },
  { id: 1227, descripcion: 'CAPITAL DE TRABAJO' },
  { id: 1228, descripcion: 'GALICIA CONVENIOS' },
  { id: 1229, descripcion: 'PBT' },
  { id: 1230, descripcion: 'DPTO. DE INFRAESTRUCTURA Y MANTENIMIENTO' },
  { id: 1231, descripcion: 'FIDEICOMISO COMERCIAL (CARTERA IRREG.)' },
  { id: 1232, descripcion: 'DPTO. INF. Y MANT.-ARQUITECTURA Y DISEÑO' },
  { id: 1233, descripcion: 'DPTO. INFRAEST. Y MANT.-INMUEBLES' },
  { id: 1234, descripcion: 'GERENCIA DE INFRAESTRUCTURA CORPORATIVA' },
  { id: 1235, descripcion: 'SUDECOR RESIDUAL' },
  { id: 1236, descripcion: 'DEPOSITO SAN MARTIN' },
  { id: 1237, descripcion: 'SOPORTE Y GESTIÓN DE LA INFORMACIÓN' },
  { id: 1238, descripcion: 'SAP - CMO' },
  { id: 1239, descripcion: 'SISTEMAS' },
  { id: 1240, descripcion: 'AUDITORÍA EXTERNA' },
  { id: 1241, descripcion: 'SISTEMAS CENTRALES Y SERVICIOS' },
  { id: 1242, descripcion: 'DPTO. NORMAS Y PROCEDIMIENTOS' },
  { id: 1243, descripcion: 'INGENIERÍA DE PROCESOS' },
  { id: 1244, descripcion: 'DPTO. TECNOLOGIA' },
  { id: 1245, descripcion: 'DPTO. DESARROLLO Y MANTENIM. DE SISTEMAS' },
  { id: 1246, descripcion: 'DPTO. ORG. Y SIST. - SUCURSALES' },
  { id: 1247, descripcion: 'MANTENIMIENTO DE SISTEMAS EN PRODUCC' },
  { id: 1248, descripcion: 'DPTO. DES. DE SIST-APOYO AUT.DE FILIALES' },
  { id: 1249, descripcion: 'PERSONAL TRANSIT. AFECTADO A PROYECTOS' },
  { id: 1250, descripcion: 'TECNOLOGIA Y PRODUCCION' },
  { id: 1251, descripcion: 'OPERACIONES E INFRAESTRUCTURA' },
  { id: 1252, descripcion: 'TECNOLOGIA Y TELECOMUNICACIONES' },
  { id: 1253, descripcion: 'ARQUITECTURA EMPRESARIAL' },
  { id: 1254, descripcion: 'GOBIERNO Y CUMPLIMIENTO DE IT' },
  { id: 1256, descripcion: 'FIRST TRUST 1 - SECURIT. DE HIPOTECAS' },
  { id: 1257, descripcion: 'FIRST TRUST II' },
  { id: 1258, descripcion: 'DATO NO PROVISTO POR RRHH' },
  { id: 1259, descripcion: 'SOPORTE DE BASE DE DATOS' },
  { id: 1260, descripcion: 'PERSONAS' },
  { id: 1261, descripcion: 'COMPENSACIONES' },
  { id: 1262, descripcion: 'ADMINISTRACIÓN Y GESTION DE LAS PERSONAS' },
  { id: 1263, descripcion: 'GESTION DEL TALENTO' },
  { id: 1264, descripcion: 'CAPACITACION Y DESARROLLO' },
  { id: 1265, descripcion: 'RELACIONES LABORALES' },
  { id: 1266, descripcion: 'APOYO INFORMATICO COMERCIAL' },
  { id: 1267, descripcion: 'COMUNICACION INTERNA Y CULTURA' },
  { id: 1268, descripcion: 'ASESORES DE PERSONAL SUCURSALES' },
  { id: 1269, descripcion: 'RECURSOS HUMANOS' },
  { id: 1270, descripcion: 'FIRST TRUST IV' },
  { id: 1271, descripcion: 'FIRST TRUST V' },
  { id: 1272, descripcion: 'BCRA I - CALCULO CER' },
  { id: 1273, descripcion: 'BCO ITAU' },
  { id: 1274, descripcion: 'DATO NO PROVISTO POR RRHH' },
  { id: 1275, descripcion: 'FIDEICOMISO BANCOS I (SUC. 975)' },
  { id: 1276, descripcion: 'FIDEICOMISO BANCOS II (SUC. 976)' },
  { id: 1278, descripcion: 'FIDEICOM. COMERCIAL' },
  { id: 1279, descripcion: 'CRÃ‰DITOS MAY. - ADM. FIDEICOMISO RENOVA' },
  { id: 1280, descripcion: 'FINANCIERA' },
  { id: 1281, descripcion: 'GESTIÓN DE ACTIVOS Y PASIVOS' },
  { id: 1282, descripcion: 'DPTO. OPERACIONES FINANCIERAS' },
  { id: 1283, descripcion: 'TESORERIA' },
  { id: 1284, descripcion: 'ADMINISTRACION DE TESORERIA' },
  { id: 1285, descripcion: 'OPERACIONES FINANCIERAS' },
  { id: 1286, descripcion: 'TESORERÍA' },
  { id: 1287, descripcion: 'BANCA DE INVERSION' },
  { id: 1288, descripcion: 'SECTOR PÚBLICO' },
  { id: 1289, descripcion: 'TRANSACCIONES FINANCIERAS' },
  { id: 1290, descripcion: 'RESEARCH' },
  { id: 1291, descripcion: 'ENTIDADES FINANCIERAS' },
  { id: 1292, descripcion: 'MERCADO DE CAPITALES Y BCA. DE INVERSIÓN' },
  { id: 1293, descripcion: 'CR MAY - ADM. CART. OP. SUBS. TAS SEPyME' },
  { id: 1294, descripcion: 'PROYECTO F.A.M.' },
  { id: 1297, descripcion: 'FIDEICOMISO GAL.PERSONALES III(SUC.747)' },
  { id: 1298, descripcion: 'BECAS DE INICIACION LABORAL' },
  { id: 1299, descripcion: 'OPERACIONES EMPRESAS' },
  { id: 1300, descripcion: 'ASESORÍA LEGAL' },
  { id: 1301, descripcion: 'GALICIA BANCA PRIVADA - CENTRO NEA' },
  { id: 1302, descripcion: 'FIDEICOMISO FLW1' },
  { id: 1303, descripcion: 'EMINENT DIGITAL' },
  { id: 1304, descripcion: 'PLANEAMIENTO' },
  { id: 1305, descripcion: 'DPTO. REL. DE INVERSORES INSTITUCIONALES' },
  { id: 1307, descripcion: 'FIDEICOMISO FINANCIERO PRIVADO FNP 1' },
  { id: 1308, descripcion: 'CONTROL DE GESTION' },
  { id: 1309, descripcion: 'DESARROLLO ESTRATEGICO Y NUEVOS NEGOCIOS' },
  { id: 1310, descripcion: 'PRESUPUESTO Y CONTROL' },
  { id: 1311, descripcion: 'PROYECTOS SARBANES - OXLEY' },
  { id: 1312, descripcion: 'RELAC. CON INV. Y CALIFICADORAS DE RSGO.' },
  { id: 1313, descripcion: 'ANALISIS INTEGRAL DE ASIG. DE RECURSOS' },
  { id: 1314, descripcion: 'CONTROL DE GESTION COMERCIAL' },
  { id: 1315, descripcion: 'CONSOLIDACION Y ANALISIS' },
  { id: 1316, descripcion: 'PLANEAMIENTO BANCA MINORISTA' },
  { id: 1317, descripcion: 'SINERGIA' },
  { id: 1318, descripcion: 'GAL BANCA PRIVADA - CENTRO CORPORATIVO' },
  { id: 1319, descripcion: 'INICIATIVAS E INFORMACION' },
  { id: 1320, descripcion: 'AUDITORÍA' },
  { id: 1321, descripcion: 'AUDITORIA FILIALES' },
  { id: 1322, descripcion: 'EQUIPO IMPLEMENTADOR PRODUCTOS EMPRESAS' },
  { id: 1323, descripcion: 'AUDITORIA DE PROCESOS CENTRALIZADOS' },
  { id: 1324, descripcion: 'AUDITORIA DE SISTEMAS' },
  { id: 1325, descripcion: 'SEGURIDAD DE LA INFORMACIÓN' },
  { id: 1326, descripcion: 'ENTRENAMIENTO OFIC AUDITORIA' },
  { id: 1327, descripcion: 'AUDITORIA DE RIESGO DE CREDITO' },
  { id: 1328, descripcion: 'AUDITORIA DE EMPRESAS VINCULADAS' },
  { id: 1329, descripcion: 'CÍRCULO DE SERVICIO DE ORIGINACIÓN' },
  { id: 1330, descripcion: 'ASESORIA IMPOSITIVA' },
  { id: 1331, descripcion: 'CORPORATIVAS 1' },
  { id: 1332, descripcion: 'CORPORATIVAS 2' },
  { id: 1333, descripcion: 'CORPORATIVAS 3' },
  { id: 1334, descripcion: 'CORPORATIVAS 4' },
  { id: 1335, descripcion: 'TARJETAS Y CONVENIOS MAYORISTAS' },
  { id: 1336, descripcion: 'PRODUCTOS Y SOLUCIONES DE VALOR' },
  { id: 1337, descripcion: 'EQUIPO DE VENTAS CORPORATIVAS' },
  { id: 1338, descripcion: 'EQUIPO PYME/ AGRO + CBE' },
  { id: 1339, descripcion: 'GESTIÓN Y OPTIMIZACIÓN DE SERVICIOS' },
  { id: 1340, descripcion: 'FUNDACION' },
  { id: 1341, descripcion: 'IPYME' },
  { id: 1342, descripcion: 'SAP' },
  { id: 1344, descripcion: 'CUENTAS & TGR' },
  { id: 1345, descripcion: 'PROYECTOS ESPECIALES - BANCA MAYORISTA' },
  { id: 1346, descripcion: 'ANALISIS DE GESTION E INCENTIVOS' },
  { id: 1347, descripcion: 'PLANEAMIENTO' },
  { id: 1348, descripcion: 'CASH MANAGMENT' },
  { id: 1349, descripcion: 'PROCESOS INTERNOS E INFORM CORPORATIVA' },
  { id: 1350, descripcion: 'INSTITUCIONAL' },
  { id: 1351, descripcion: 'OTROS GASTOS DE SUCURSALES' },
  { id: 1352, descripcion: 'INSTITUCIONALES BID' },
  { id: 1353, descripcion: 'VENDIMIA' },
  { id: 1354, descripcion: 'PROVINCIA DE CORDOBA - BANCO SUDECOR' },
  { id: 1355, descripcion: 'CORREO ARGENTINO' },
  { id: 1356, descripcion: 'FIDELIZACION Y RETENCION' },
  { id: 1357, descripcion: 'PROGRAMAS COMERCIALES' },
  { id: 1358, descripcion: 'EQUIPO PYME/AGRO + CBE/INTERIOR' },
  { id: 1359, descripcion: 'PROGRAMA LEAN' },
  { id: 1360, descripcion: 'PERSONAL SUPERIOR' },
  { id: 1362, descripcion: 'MONEY MARKET' },
  { id: 1363, descripcion: 'SECTOR PUBLICO Y DEUDA EXTERNA' },
  { id: 1364, descripcion: 'CAMBIOS' },
  { id: 1365, descripcion: 'COMERCIAL' },
  { id: 1366, descripcion: 'SOPORTE COMERCIAL CORPORATIVO' },
  { id: 1367, descripcion: 'PROYECTO PEOPLENET' },
  { id: 1368, descripcion: 'DESARROLLO GERENCIAL' },
  { id: 1369, descripcion: 'EXPERIENCIA GALICIA' },
  { id: 1370, descripcion: 'GASTOS COMUNES CASA MATRIZ' },
  { id: 1371, descripcion: 'CÍRCULO DE SERVICIO EVERYDAY BANKING' },
  { id: 1372, descripcion: 'BACK FINANCIERO INTEGRADO' },
  { id: 1373, descripcion: 'PRODUCTOS Y TARJETAS' },
  { id: 1374, descripcion: 'DESARROLLO DE COMERCIOS' },
  { id: 1375, descripcion: 'GESTION DE TESORERIA DE EMPRESAS' },
  { id: 1376, descripcion: 'INVERSIONES Y SEGUROS' },
  { id: 1377, descripcion: 'LAB DE INNOVACION' },
  { id: 1380, descripcion: 'ZONA METRO I' },
  { id: 1381, descripcion: 'ZONA METRO III' },
  { id: 1382, descripcion: 'ZONA METRO II' },
  { id: 1383, descripcion: 'ZONA SUR' },
  { id: 1384, descripcion: 'ZONA PILAR' },
  { id: 1385, descripcion: 'ZONA NEA' },
  { id: 1386, descripcion: 'ZONA NORTE' },
  { id: 1387, descripcion: 'ZONA MEDITERRÁNEA' },
  { id: 1388, descripcion: 'ZONA OESTE' },
  { id: 1389, descripcion: 'MAR Y PAMPA' },
  { id: 1390, descripcion: 'ZONA MAR DEL PLATA' },
  { id: 1391, descripcion: 'ZONA METRO IV' },
  { id: 1392, descripcion: 'ZONA PROVINCIA DE BS. AS.' },
  { id: 1393, descripcion: 'ZONA BELGRANO' },
  { id: 1394, descripcion: 'ZONA SANTA FE / NEA' },
  { id: 1395, descripcion: 'ZONA CORDILLERA' },
  { id: 1396, descripcion: 'ZONA NEA' },
  { id: 1397, descripcion: 'ZONA PATAGONIA' },
  { id: 1398, descripcion: 'Zona Metro V ' },
  { id: 1400, descripcion: 'BANCA MAYORISTA' },
  { id: 1401, descripcion: 'CRÉDITO SECTOR PÚBLICO FINANCIERO Y MERC' },
  { id: 1402, descripcion: 'GESTION DE INFORMACION PREVENTIVA' },
  { id: 1403, descripcion: 'ANÁLISIS SECTORIAL Y AMBIENTAL' },
  { id: 1404, descripcion: 'OTORGAMIENTO INDIVIDUOS' },
  { id: 1405, descripcion: 'GESTIÓN DE LA INFORMACIÓN' },
  { id: 1406, descripcion: 'RIESGO OPERACIONAL Y PREVENCIÓN DE FRAUD' },
  { id: 1407, descripcion: 'POLITICAS DE CREDITO' },
  { id: 1408, descripcion: 'RIESGO FINANCIERO' },
  { id: 1409, descripcion: 'ZONA CORDILLERA' },
  { id: 1410, descripcion: 'GESTION PREVENTIVA COMERCIAL' },
  { id: 1411, descripcion: 'POLITICAS Y ESTRATEGIAS' },
  { id: 1412, descripcion: 'CRÉDITO CORPORATIVAS' },
  { id: 1413, descripcion: 'ANALISIS DE CREDITOS' },
  { id: 1414, descripcion: 'ANALISIS CREDITICIO AGROPECUARIO' },
  { id: 1415, descripcion: 'CONTROL DE RIESGOS' },
  { id: 1416, descripcion: 'SUPERVISION Y CLASIFICACION DE CREDITOS' },
  { id: 1417, descripcion: 'SEGUIMIENTO DE CARTERA' },
  { id: 1418, descripcion: 'INGRESO DE BALANCE' },
  { id: 1419, descripcion: 'OTORGAMIENTO ESTANDARIZADO' },
  { id: 1420, descripcion: 'MEDIANAS METRO' },
  { id: 1421, descripcion: 'MES 1' },
  { id: 1422, descripcion: 'MES 2' },
  { id: 1423, descripcion: 'MES 3' },
  { id: 1424, descripcion: 'MES 4' },
  { id: 1425, descripcion: 'REGIONAL SANTA FE' },
  { id: 1426, descripcion: 'MEDIANAS EMPRESAS INTERIOR' },
  { id: 1427, descripcion: 'ATENCIÓN TELEFÓNICA EMPRESAS' },
  { id: 1428, descripcion: 'ABASTECIMIENTO ESTRATEGICO' },
  { id: 1429, descripcion: 'PYMES' },
  { id: 1430, descripcion: 'AGRO METRO' },
  { id: 1431, descripcion: 'AGRO INTERIOR' },
  { id: 1432, descripcion: 'AGRO PES' },
  { id: 1433, descripcion: 'AGRO METROPOLITANA' },
  { id: 1434, descripcion: 'NEGOCIOS Y PYMES' },
  { id: 1435, descripcion: 'PRODUCTOS ACTIVOS Y CONVENIOS' },
  { id: 1436, descripcion: 'AGRO METRO II' },
  { id: 1437, descripcion: 'CADENA DE VALOR' },
  { id: 1438, descripcion: 'AGRO PES' },
  { id: 1439, descripcion: 'AGROPECUARIAS' },
  { id: 1440, descripcion: 'P.C.O' },
  { id: 1441, descripcion: 'PLANEAMIENTO Y CONTROL DE OTORGAMIENTO' },
  { id: 1442, descripcion: 'P.C.O. CORDOBA' },
  { id: 1443, descripcion: 'P.C.O. CUYO' },
  { id: 1444, descripcion: 'P.C.O. SANTA FE' },
  { id: 1445, descripcion: 'BPO MORA MINORISTA' },
  { id: 1446, descripcion: 'HERRAMIENTAS DE DECISION CREDITICIA' },
  { id: 1447, descripcion: 'ADMINISTRACION DE CARTERA VIVA' },
  { id: 1448, descripcion: 'GESTIÓN DE CLIENTES EN MORA MAYORISTA' },
  { id: 1449, descripcion: 'AUDITORÍA JURÍDICA' },
  { id: 1450, descripcion: 'INSPECCION BCRA' },
  { id: 1451, descripcion: 'ANÁLISIS DE PORTFOLIO' },
  { id: 1452, descripcion: 'SUPERVISIÓN Y REVISIÓN DE CARTERA' },
  { id: 1453, descripcion: 'GESTIÓN DE CARTERA' },
  { id: 1454, descripcion: 'PLANEAMIENTO COMERCIAL - CALL CENTER' },
  { id: 1455, descripcion: 'PUNTOS DE VENTAS' },
  { id: 1456, descripcion: 'CREDITO MINORISTA' },
  { id: 1457, descripcion: 'RIESGO COMPAÑIAS VINCULADAS' },
  { id: 1458, descripcion: 'PROGRAMA LEAN SUCURSALES' },
  { id: 1460, descripcion: 'VENTA MINORISTA - PUERTO MADRYN' },
  { id: 1461, descripcion: 'VENTA MINORISTA - REGIONAL NEA' },
  { id: 1462, descripcion: 'VENTA MINORISTA - TUCUMAN' },
  { id: 1463, descripcion: 'VTA. MINORISTA - JUNIN' },
  { id: 1464, descripcion: 'VTA. MINORISTA - SAN JUAN' },
  { id: 1465, descripcion: 'VENTA MINORISTA - NEUQUÃ‰N' },
  { id: 1466, descripcion: 'VTA. MINORISTA - SAN LUIS' },
  { id: 1467, descripcion: 'VENTA MINORISTA - SALTA' },
  { id: 1468, descripcion: 'VTA. MINORISTA - RIO CUARTO' },
  { id: 1469, descripcion: 'VENTA MINORISTA - COMODORO RIVADAVIA' },
  { id: 1470, descripcion: 'VENTA MINORISTA - USHUAIA' },
  { id: 1471, descripcion: 'VENTA MINORISTA - RIO GRANDE' },
  { id: 1472, descripcion: 'CANALES DE TERCEROS' },
  { id: 1473, descripcion: 'GALICIA CONECTA Y VTA. PYME' },
  { id: 1484, descripcion: 'SEGMENTO EMPRESAS' },
  { id: 1485, descripcion: 'SEGMENTO CORPORATIVAS' },
  { id: 1486, descripcion: 'PROPUESTA DE VALOR INTEGRAL AGRONEGOCIOS' },
  { id: 1487, descripcion: 'CAPTACION Y DESARROLLO AGRONEGOCIOS' },
  { id: 1488, descripcion: 'COMPLIANCE' },
  { id: 1489, descripcion: 'ADM. CENT. DE TERMINALES DE AUTOSERVICIO' },
  { id: 1490, descripcion: 'RENTA ALTA' },
  { id: 1491, descripcion: 'NEGOCIOS Y PROFESIONALES' },
  { id: 1492, descripcion: 'RENTAS MEDIAS' },
  { id: 1493, descripcion: 'RENTAS BAJAS' },
  { id: 1494, descripcion: 'CUSTOMER INTELLIGENCE' },
  { id: 1495, descripcion: 'CONVENIOS Y HABERES' },
  { id: 1496, descripcion: 'INVERSIONES Y CUENTAS' },
  { id: 1497, descripcion: 'PRESTAMOS' },
  { id: 1498, descripcion: 'SEGUROS' },
  { id: 1499, descripcion: 'MEDIOS DE PAGOS' },
  { id: 1500, descripcion: 'FIDEICOMISO FINANC. GALICIA LEASING II' },
  { id: 1501, descripcion: 'OPERATORIA TBNE' },
  { id: 1502, descripcion: 'COMERCIAL CBE' },
  { id: 1503, descripcion: 'CBE REGION CABA' },
  { id: 1504, descripcion: 'CBE REGION MEDITERRANEA' },
  { id: 1506, descripcion: 'CBE REGION BUENOS AIRES' },
  { id: 1507, descripcion: 'CBE REGION GRAN BUENOS AIRES' },
  { id: 1508, descripcion: 'CBE REGION ROSARIO LITORAL' },
  { id: 1509, descripcion: 'CBE REGION CUYO PATAGONIA' },
  { id: 1510, descripcion: 'OPERERATORIA CENTR. T.NEVADA (SUC. 910)' },
  { id: 1511, descripcion: 'SAN JUAN' },
  { id: 1518, descripcion: 'VINCULADAS' },
  { id: 1521, descripcion: 'AGRO MATRIZ' },
  { id: 1522, descripcion: 'CBE1 MAR Y SIERRAS' },
  { id: 1523, descripcion: 'AGRO REMOTO' },
  { id: 1524, descripcion: 'TOP AGRO' },
  { id: 1526, descripcion: 'PROCRED - RIO NEGRO (CASA N826)' },
  { id: 1527, descripcion: 'COMPRAS DE SERVICIOS' },
  { id: 1531, descripcion: 'CBE2 BS AS NORTE' },
  { id: 1532, descripcion: 'CBE GBA NORTE' },
  { id: 1533, descripcion: 'CBE2 NEA' },
  { id: 1534, descripcion: 'CBE2 LITORAL' },
  { id: 1535, descripcion: 'CBE JUNIN' },
  { id: 1536, descripcion: 'TN SAN JUAN (SUC. 936)' },
  { id: 1537, descripcion: 'TN LA PAMPA (SUC. 937)' },
  { id: 1538, descripcion: 'TN FORMOSA (SUC. 938)' },
  { id: 1539, descripcion: 'TN BUENOS AIRES-SAN NICOLÁS (SUC. 939)' },
  { id: 1540, descripcion: 'TN CATAMARCA (SUC. 940)' },
  { id: 1541, descripcion: 'TN RESISTENCIA (SUC. 941)' },
  { id: 1542, descripcion: 'TN MENDOZA' },
  { id: 1543, descripcion: 'TN PTO. MADRYN (SUC. 943)' },
  { id: 1544, descripcion: 'TN CATEDRAL (SUC. 944)' },
  { id: 1545, descripcion: 'TN CORRIENTES (SUC. 945)' },
  { id: 1547, descripcion: 'TN CONCORDIA ( SUC. 947)' },
  { id: 1548, descripcion: 'TN JUJUY (SUC. 948)' },
  { id: 1549, descripcion: 'TN LA RIOJA (SUC. 949)' },
  { id: 1550, descripcion: 'TN POSADAS (SUC. 950)' },
  { id: 1551, descripcion: 'TN NEUQUÉN (SUC. 951)' },
  { id: 1552, descripcion: 'TN GRAL. ROCA (SUC. 952)' },
  { id: 1553, descripcion: 'TN SALTA CENTRO (SUC. 953)' },
  { id: 1554, descripcion: 'TN SAN LUIS (SUC. 954)' },
  { id: 1555, descripcion: 'TN RIO GALLEGOS (SUC. 955)' },
  { id: 1559, descripcion: 'TN SANTIAGO DEL ESTERO (SUC. 959)' },
  { id: 1560, descripcion: 'TN ROSARIO (SUC. 960)' },
  { id: 1561, descripcion: 'TN TUCUMÁN (SUC. 961)' },
  { id: 1562, descripcion: 'TN MENDOZA (SUC. 962)' },
  { id: 1565, descripcion: 'TN OPERATORIA CENTRALIZADA' },
  { id: 1566, descripcion: 'ADM. DE SINIESTROS POR SEGUROS DE VIDA' },
  { id: 1567, descripcion: 'T. NEVADA - SANTIAGO DEL ESTERO(SUC.967)' },
  { id: 1568, descripcion: 'CBE CORDOBA' },
  { id: 1569, descripcion: 'CBE NOA' },
  { id: 1570, descripcion: 'CBE1 RIO CUARTO' },
  { id: 1571, descripcion: 'CBE SALTA' },
  { id: 1572, descripcion: 'CBE3 MICROCENTRO' },
  { id: 1573, descripcion: 'CBE3 GBA SUR' },
  { id: 1574, descripcion: 'CBE3 BELGRANO' },
  { id: 1575, descripcion: 'CBE3 MACROCENTRO' },
  { id: 1576, descripcion: 'CBE PATERNAL' },
  { id: 1577, descripcion: 'CBE CUYO' },
  { id: 1578, descripcion: 'CBE PATAGONIA' },
  { id: 1579, descripcion: 'CBE GBA OESTE' },
  { id: 1582, descripcion: 'FIDEICOMISO FINANCIERO PERSONALES VI' },
  { id: 1583, descripcion: 'FIDEICOMISO FINANCIERO PERSONALES VII' },
  { id: 1584, descripcion: 'FIDEICOMISO FINANCIERO PERSONALES VIII' },
  { id: 1585, descripcion: 'CBE TANDIL' },
  { id: 1586, descripcion: 'PROCRED - TIERRA DEL FUEGO (CASA N825)' },
  { id: 1587, descripcion: 'CBE SALTA' },
  { id: 1588, descripcion: 'Fideicomiso Individuos 01' },
  { id: 1589, descripcion: 'CBE4 COMODORO RIVADAVIA' },
  { id: 1590, descripcion: 'COBRANZAS CARTERA CFA' },
  { id: 1591, descripcion: 'CFA SAN JUAN' },
  { id: 1592, descripcion: 'CFA LA PAMPA' },
  { id: 1593, descripcion: 'CFA FORMOSA' },
  { id: 1594, descripcion: 'CFA BUENOS AIRES-SAN NICOLAS' },
  { id: 1595, descripcion: 'CFA CATAMARCA' },
  { id: 1596, descripcion: 'CFA RESISTENCIA' },
  { id: 1597, descripcion: 'CFA MENDOZA' },
  { id: 1598, descripcion: 'CFA PTO. MADRYN' },
  { id: 1599, descripcion: 'CFA CATEDRAL' },
  { id: 1600, descripcion: 'CFA CORRIENTES' },
  { id: 1601, descripcion: 'CFA TIERRA DEL FUEGO' },
  { id: 1602, descripcion: 'CFA CONCORDIA' },
  { id: 1603, descripcion: 'CFA JUJUY' },
  { id: 1604, descripcion: 'CFA LA RIOJA' },
  { id: 1605, descripcion: 'CFA POSADAS' },
  { id: 1606, descripcion: 'CFA NEUQUEN' },
  { id: 1607, descripcion: 'CFA GRAL. ROCA' },
  { id: 1608, descripcion: 'CFA SALTA CENTRO' },
  { id: 1609, descripcion: 'CFA SAN LUIS' },
  { id: 1610, descripcion: 'CFA RIO GALLEGOS' },
  { id: 1611, descripcion: 'CFA CAPITAL FEDERAL' },
  { id: 1612, descripcion: 'CFA SANTIAGO DEL ESTERO' },
  { id: 1613, descripcion: 'CFA ROSARIO' },
  { id: 1614, descripcion: 'CFA TUCUMAN' },
  { id: 1616, descripcion: 'BIENES PENDIENTES DE UTILIZACIÓN' },
  { id: 1617, descripcion: 'DEPOSITO RAMOS MEJIA' },
  { id: 1618, descripcion: 'DEPOSITO BOEDO' },
  { id: 1619, descripcion: 'DEPOSITO CASA MATRIZ - MOBILIARIO' },
  { id: 1620, descripcion: 'DEPOSITO CASA MATRIZ - MAQ. Y EQUIPOS' },
  { id: 1621, descripcion: 'DEPOSITO DPTO. ORGANIZACION' },
  { id: 1622, descripcion: 'DEPOSITO PROC. DE DATOS - TELEFONIA' },
  { id: 1623, descripcion: 'DEPOSITO PROC. DE DATOS - COMPUTADOR' },
  { id: 1624, descripcion: 'DEPOSITO DPTO. INFRAESTRUCTURA Y MANT' },
  { id: 1625, descripcion: 'DEPOSITO PODESTA' },
  { id: 1631, descripcion: 'PROCRED - PCIA. BUENOS AIRES' },
  { id: 1632, descripcion: 'PROCRED - CATAMARCA' },
  { id: 1633, descripcion: 'PROCRED - CORDOBA' },
  { id: 1634, descripcion: 'PROCRED - CORRIENTES' },
  { id: 1635, descripcion: 'PROCRED - ENTRE RIOS' },
  { id: 1636, descripcion: 'PROCRED - JUJUY' },
  { id: 1637, descripcion: 'PROCRED - MENDOZA' },
  { id: 1638, descripcion: 'PROCRED - LA RIOJA' },
  { id: 1639, descripcion: 'PROCRED - SALTA' },
  { id: 1640, descripcion: 'PROCRED - SAN LUIS' },
  { id: 1641, descripcion: 'PROCRED - SANTA FE' },
  { id: 1642, descripcion: 'PROCRED - SANTIAGO DEL ESTERO' },
  { id: 1643, descripcion: 'PROCRED - TUCUMAN' },
  { id: 1644, descripcion: 'PROCRED - CHACO' },
  { id: 1645, descripcion: 'PROCRED - CHUBUT' },
  { id: 1646, descripcion: 'PROCRED - FORMOSA' },
  { id: 1647, descripcion: 'PROCRED - MISIONES' },
  { id: 1648, descripcion: 'PROCRED - NEUQUEN' },
  { id: 1649, descripcion: 'PROCRED - LA PAMPA' },
  { id: 1650, descripcion: 'PROCRED - SAN JUAN' },
  { id: 1651, descripcion: 'PROCRED - SANTA CRUZ' },
  { id: 1652, descripcion: 'Cobranza Banco Columbia-Buenos Aires' },
  { id: 1653, descripcion: 'Cobranza Banco Columbia-Capital Federal' },
  { id: 1654, descripcion: 'Cobranza Banco Columbia-Catamarca' },
  { id: 1655, descripcion: 'Cobranza Banco Columbia-Chaco' },
  { id: 1656, descripcion: 'Cobranza Banco Columbia-Chubut' },
  { id: 1657, descripcion: 'Cobranza Banco Columbia-Cordoba' },
  { id: 1658, descripcion: 'Cobranza Banco Columbia-Corrientes' },
  { id: 1659, descripcion: 'Cobranza Banco Columbia-Jujuy' },
  { id: 1660, descripcion: 'PROVISIONES' },
  { id: 1661, descripcion: 'Cobranza Banco Columbia-Misiones' },
  { id: 1662, descripcion: 'Cobranza Banco Columbia-Neuquen' },
  { id: 1663, descripcion: 'Cobranza Banco Columbia-Rio Negro' },
  { id: 1664, descripcion: 'Cobranza Banco Columbia-Salta' },
  { id: 1665, descripcion: 'Cobranza Banco Columbia-San Juan' },
  { id: 1666, descripcion: 'Cobranza Banco Columbia-San Luis' },
  { id: 1667, descripcion: 'Cobranza Banco Columbia-Santa Fe' },
  { id: 1668, descripcion: 'Cobranza Banco Columbia-Santiago del Est' },
  { id: 1669, descripcion: 'Cobranza Banco Columbia-Tucuman' },
  { id: 1670, descripcion: 'AJUSTES PARTIDAS DE REEXPRESIÓN' },
  { id: 1680, descripcion: 'RESULTADOS APROPIADOS A FILIALES' },
  { id: 1690, descripcion: 'GERENCIA EXPERIENCIA DEL CLIENTE' },
  { id: 1691, descripcion: 'TRIBU VIAJES DEL CLIENTE' },
  { id: 1692, descripcion: 'CENTRO DE EXCELENCIA' },
  { id: 1693, descripcion: 'TRANSFORMACIÓN Y EFICIENCIA' },
  { id: 1694, descripcion: 'GESTIÓN DE LA DEMANDA Y PMO' },
  { id: 1695, descripcion: 'GERENCIA DE CANALES INDIRECTOS' },
  { id: 1696, descripcion: 'CANAL DE VENTA PYME' },
  { id: 1697, descripcion: 'DIGITAL' },
  { id: 1698, descripcion: 'MARKETING DIGITAL' },
  { id: 1699, descripcion: 'COMERCIAL' },
  { id: 1700, descripcion: 'EXCEDENCIA' },
  { id: 1701, descripcion: 'GESTION CENTRALIZADA DE SUCURSALES' },
  { id: 1702, descripcion: 'MODERNIZACION DEL CANAL' },
  { id: 1703, descripcion: 'SECRETARIA DE CREDITOS' },
  { id: 1704, descripcion: 'GESTION DEL CAPITAL' },
  { id: 1705, descripcion: 'SOPORTE AL NEGOCIO' },
  { id: 1706, descripcion: 'VENTA MINORISTA - SUR' },
  { id: 1707, descripcion: 'VENTA MINORISTA - METRO II' },
  { id: 1708, descripcion: 'VENTA MINORISTA - METRO IV Y NORTE' },
  { id: 1709, descripcion: 'VENTA MINORISTA - OESTE' },
  { id: 1710, descripcion: 'VENTA MINORISTA - MEDITERRANEA' },
  { id: 1711, descripcion: 'VENTA MINORISTA - MAR Y PAMPA' },
  { id: 1712, descripcion: 'VENTA MINORISTA - SANTA FE Y NEA' },
  { id: 1713, descripcion: 'VENTA MINORISTA - CORDILLERA' },
  { id: 1714, descripcion: 'VENTA MINORISTA - METRO III' },
  { id: 1715, descripcion: 'EMISIONES BANCO' },
  { id: 1716, descripcion: 'CORPORATIVAS SERVICIOS TRANSACCIONALES' },
  { id: 1717, descripcion: 'CREDITO MAYORISTA' },
  { id: 1718, descripcion: 'CONTROL CONTABLE' },
  { id: 1719, descripcion: 'OFICIOS JURÍDICOS' },
  { id: 1720, descripcion: 'VENTA MINORISTA - NORTE' },
  { id: 1721, descripcion: 'VENTA MINORISTA - METRO I' },
  { id: 1722, descripcion: 'VENTA MINORISTA - METRO III' },
  { id: 1723, descripcion: 'VENTA MINORISTA - PCIA. BS.AS.' },
  { id: 1724, descripcion: 'PROYECTO SAM' },
  { id: 1725, descripcion: 'LIC GREMIAL' },
  { id: 1727, descripcion: 'LIC. GREMIAL MAR DEL PLATA' },
  { id: 1728, descripcion: 'M & A FOCUS' },
  { id: 1729, descripcion: 'GALICIA CONECTA EMINENT' },
  { id: 1730, descripcion: 'EFICIENCIA Y DESEMPEÃ‘O' },
  { id: 1731, descripcion: 'CENTRO DE SOLUCIONES ANALITICAS' },
  { id: 1733, descripcion: 'GESTION DEL NEGOCIO FIDUCIARIO' },
  { id: 1734, descripcion: 'POLITICA DE RECUPERO' },
  { id: 1735, descripcion: 'CANALES DIGITALES' },
  { id: 1736, descripcion: 'SERVICIOS' },
  { id: 1737, descripcion: 'RESEARCH' },
  { id: 1738, descripcion: 'GESTIÃ“N INTEGRAL DE EGRESOS' },
  { id: 1739, descripcion: 'FINANCIAMIENTO ESTRUCTURADO' },
  { id: 1740, descripcion: 'GCIA. COMERCIAL AGRONEGOCIOS' },
  { id: 1741, descripcion: 'SERVICIOS Y CONSULTORIA' },
  { id: 1742, descripcion: 'MODELOS INDIVIDUOS' },
  { id: 1743, descripcion: 'INFORMACION Y PROYECTOS' },
  { id: 1744, descripcion: 'MODELOS NO INDIVIDUOS' },
  { id: 1745, descripcion: 'FINANCIAMIENTO ESTRATEGICO' },
  { id: 1746, descripcion: 'TRIBU DATA & ANALYTICS' },
  { id: 1747, descripcion: 'CDO (CHIEF DATA OFFICER)' },
  { id: 1748, descripcion: 'RECUPERO DE CRÃ‰DITOS' },
  { id: 1750, descripcion: 'VARIOS' },
  { id: 1751, descripcion: 'PREBANCO' },
  { id: 1752, descripcion: 'RESERVA' },
  { id: 1753, descripcion: 'MAILROOM' },
  { id: 1754, descripcion: 'VENTA MINORISTA - NEA / NOA' },
  { id: 1755, descripcion: 'VENTA MINORISTA - PATAGONIA' },
  { id: 1756, descripcion: 'VENTA MINORISTA - METRO V' },
  { id: 1757, descripcion: 'CRÉDITOS MAYORISTA' },
  { id: 1758, descripcion: 'PRODUCTOS' },
  { id: 1759, descripcion: 'CBE REGIÓN LITORAL NEA' },
  { id: 1760, descripcion: 'PLATAFORMA COMERCIAL FIN MAQ & TRANSP' },
  { id: 1761, descripcion: 'CBE NEGOCIOS TRANSACCIONALES' },
  { id: 1762, descripcion: 'NODO - MEDITERRANEA' },
  { id: 1763, descripcion: 'NODO - MAR Y PAMPA' },
  { id: 1764, descripcion: 'NODO - NORTE' },
  { id: 1765, descripcion: 'NODO - METRO V' },
  { id: 1767, descripcion: 'OPERACIONES MINORISTAS' },
  { id: 1768, descripcion: 'GESTIÓN DE LA CAPACIDAD' },
  { id: 1769, descripcion: 'LOGÍSTICA DE DOCUMENTACIÓN' },
  { id: 1770, descripcion: 'LOGISTICA DE EFECTIVO' },
  { id: 1771, descripcion: 'GERENCIA DE INFRAESTRUCTURA SUCURSALES' },
  { id: 1772, descripcion: 'OBRAS EN SUCURSALES' },
  { id: 1773, descripcion: 'MANTENIMIENTO DE LA RED DE SUCURSALES' },
  { id: 1774, descripcion: 'ANALISIS Y ESTRATEGIAS' },
  { id: 1775, descripcion: 'SUELDOS SUSPENDIDOS' },
  { id: 1776, descripcion: 'TRANSFORMACION DIGITAL' },
  { id: 1777, descripcion: 'GESTION Y PREVENCION DEL FRAUDE' },
  { id: 1778, descripcion: 'MOVE' },
  { id: 1779, descripcion: 'GERENCIA DE CALIDAD Y DEVOPS' },
  { id: 1780, descripcion: 'GESTION DE PROVEDORES Y TESORERIA' },
  { id: 1781, descripcion: 'PROYECTO BANKTRADE' },
  { id: 1782, descripcion: 'COMPRAS DE INFRAESTRUCTURA' },
  { id: 1783, descripcion: 'DATA & ANALYTICS -TRANSFORMACION DIGITAL' },
  { id: 1784, descripcion: 'Ajuste por ReexpresiÃ³n NIIF' },
  { id: 1785, descripcion: 'GALICIA PREFER CONECTA' },
  { id: 1786, descripcion: 'DISEÑO' },
  { id: 1787, descripcion: 'ASSET MANAGEMENT' },
  { id: 1788, descripcion: 'TRIBU DE COBROS Y PAGOS' },
  { id: 1789, descripcion: 'TRIBU EVERYDAY BANKING' },
  { id: 1790, descripcion: 'GALICIA INVERSIONES ASIGNADO 1' },
  { id: 1791, descripcion: 'COMITÃ‰ DE CONDUCTA' },
  { id: 1792, descripcion: 'TRIBU LENDING' },
  { id: 1793, descripcion: 'TRIBU OMNICANALIDAD' },
  { id: 1794, descripcion: 'WAR ROOM DE XSELL DE PRÉSTAMOS Y SEGUROS' },
  { id: 1795, descripcion: 'COMEX Y SERVICIOS TRANSACCIONALES' },
  { id: 1800, descripcion: 'MATERNIDAD' },
  { id: 1803, descripcion: 'PLAY SISTÃ‰MICO DE PAGOS' },
  { id: 1804, descripcion: 'TRIBU DE PRODUCTOS TECH' },
  { id: 1805, descripcion: 'DATA ANALYTICS IT' },
  { id: 1825, descripcion: 'PLAN CARRERA (TRAINING)' },
  { id: 1826, descripcion: 'PLAN CARRERA (OTROS)' },
  { id: 1885, descripcion: 'ENFERMEDAD LARGO TRATAMIENTO' },
  { id: 1999, descripcion: 'CURSANTES' },
  { id: 2000, descripcion: 'CASA MATRIZ - CAJA' },
  { id: 2001, descripcion: 'CASA MATRIZ - CTAS. CTES' },
  { id: 2002, descripcion: 'CASA MATRIZ - GCIA. ADMINISTRATIVA' },
  { id: 2003, descripcion: 'CASA MATRIZ - GCIA. COMERCIAL' },
  { id: 2004, descripcion: 'CASA MATRIZ - MESA DE CONSULTAS' },
  { id: 2005, descripcion: 'CASA MATRIZ - CTAS. CTES' },
  { id: 2006, descripcion: 'CASA MATRIZ - INFORMES AL PUBLICO' },
  { id: 2007, descripcion: 'CASA MATRIZ - CENTRO DE VENTAS' },
  { id: 2008, descripcion: 'CASA MATRIZ - CENTRO DE INVERSIONES' },
  { id: 2009, descripcion: 'CASA MATRIZ - CAJAS' },
  { id: 2010, descripcion: 'CASA MATRIZ - SECTOR OPERATIVO' },
  { id: 2011, descripcion: 'CASA MATRIZ - SECTOR COMERCIAL MINORISTA' },
  { id: 2012, descripcion: 'CASA MATRIZ - REG. DE FIRMAS DE C.C' },
  { id: 2013, descripcion: 'CASA MATRIZ - DIGITALIZACION DE FIRMAS' },
  { id: 2014, descripcion: 'CASA MATRIZ - CAJAS DE SEGURIDAD' },
  { id: 2015, descripcion: 'CASA MATRIZ - SECTOR OPERATIVO' },
  { id: 2016, descripcion: 'CASA MATRIZ - ANEXO SERV. ESPECIALES' },
  { id: 2017, descripcion: 'CASA MATRIZ - ANEXO CASA DE CAMBIO' },
  { id: 2018, descripcion: 'CASA MATRIZ - TESORO' },
  { id: 2050, descripcion: 'Centro de costo 2050' },
  { id: 2090, descripcion: 'TARJETAS REGIONALES20' },
  { id: 2092, descripcion: 'GALICIA SEGUROS S.A.' },
  { id: 2097, descripcion: 'DATO NO PROVISTO POR RRHH' },
  { id: 2222, descripcion: 'GALICIA PRUEBA MODIFICADA' },
  { id: 2223, descripcion: 'GALICIA PRUEBA' },
  { id: 2280, descripcion: 'GALICIA VALORES' },
  { id: 2394, descripcion: 'INTELIGENCIA COMERCIAL' },
  { id: 2495, descripcion: 'CONVENIOS Y HABERES' },
  { id: 3000, descripcion: 'CASA DE RODRIGO' },
  { id: 4000, descripcion: 'PRUEBA DIRECCION' },
  { id: 5000, descripcion: 'PRUEBA NUMERO 3' },
  { id: 5001, descripcion: '1299-Legales' },
  { id: 5002, descripcion: '1199-AuditorÃ­a' },
  { id: 5003, descripcion: '1399-Recursos Humanos' },
  { id: 5004, descripcion: '1999-Gcia. Adm y Finanzas' },
  { id: 5005, descripcion: '3599-Planeamiento' },
  { id: 5006, descripcion: '3599-Tecnica' },
  { id: 5007, descripcion: '1999-Caución' },
  { id: 5008, descripcion: '1999-Tecnica Empresas' },
  { id: 5009, descripcion: '2099-Impuestos' },
  { id: 5010, descripcion: '2099-Contabilidad y Soc.' },
  { id: 5011, descripcion: '3099-Tesorería' },
  { id: 5012, descripcion: '3099-Inversiones' },
  { id: 5013, descripcion: '4099-Gcia de Operaciones' },
  { id: 5014, descripcion: '7099-Administracion Broker' },
  { id: 5015, descripcion: '3051-Cobranzas' },
  { id: 5016, descripcion: '4599-compras y Serv Grales' },
  { id: 5017, descripcion: '4555-Beneficios' },
  { id: 5018, descripcion: '4556-Suscripción' },
  { id: 5019, descripcion: '4053-Emisión' },
  { id: 5020, descripcion: '6599-CAC' },
  { id: 5021, descripcion: '6099-Gcia Comercial' },
  { id: 5022, descripcion: '6199-Marketing' },
  { id: 5023, descripcion: '6699-CVT' },
  { id: 5024, descripcion: '6799-Banca minorista' },
  { id: 5025, descripcion: '6999-Tarjetas Regionales' },
  { id: 5026, descripcion: '6499-Negocios Corporativos' },
  { id: 5027, descripcion: '8099-Gcia de Exp del Cliente' },
  { id: 5028, descripcion: '5099-Gcia Sistemas' },
  { id: 5029, descripcion: '5199-ADN 2020' },
  { id: 5030, descripcion: '9999-Dist Gral' },
  { id: 5031, descripcion: '7199-Originación Empresas' },
  { id: 5032, descripcion: '7299-Originación Individuos' },
  { id: 5033, descripcion: '7399-Facturación y Recaudación' },
  { id: 5100, descripcion: 'PRUEBA NUMERO 4' },
  { id: 5300, descripcion: 'PRUEBA 555' },
  { id: 5400, descripcion: 'PRUEBA 666' },
  { id: 5500, descripcion: 'PRUEBA 777' },
  { id: 5555, descripcion: 'BUROCRACIA SINDICAL' },
  { id: 5600, descripcion: 'PRUEBA 888' },
  { id: 6002, descripcion: 'GAL MOBILIARIA S.A.' },
  { id: 6003, descripcion: 'GALICIA INTERNACIONAL' },
  { id: 6004, descripcion: 'PRODUCTOS - GALICIA INTERNACIONAL' },
  { id: 6005, descripcion: 'ADMINISTRATIVO - GALICIA INTERNACIONAL' },
  { id: 6006, descripcion: 'SISTEMAS - GALICIA INTERNACIONAL' },
  { id: 6007, descripcion: 'REPRESENTACION - GALICIA INTERNACIONAL' },
  { id: 6008, descripcion: 'SECRET. Y RECEP. - GALICIA INTERNACIONAL' },
  { id: 6009, descripcion: 'PRESTAMOS - GALICIA INTERNACIONAL' },
  { id: 6010, descripcion: 'ADMINISTRACION - SANTIAGO DE COMPOSTELA' },
  { id: 6011, descripcion: 'COMERCIAL - SANTIAGO DE COMPOSTELA' },
  { id: 6012, descripcion: 'SECRET. Y RECEP.-SANTIAGO DE COMPOSTELA' },
  { id: 6013, descripcion: 'INVICTUS' },
  { id: 6014, descripcion: 'GALICIA VALORES' },
  { id: 6015, descripcion: 'GALICIA FACTORING' },
  { id: 6016, descripcion: 'GALICIA ADM. DE FONDOS' },
  { id: 6017, descripcion: 'SECTOR VELOSO - GAL. ADM. DE FONDOS' },
  { id: 6018, descripcion: 'CEBALLOS - GALICIA CAPITAL MARKETS' },
  { id: 6019, descripcion: 'LETT - GALICIA CAPITAL MARKETS' },
  { id: 6020, descripcion: 'OROMI - GALICIA CAPITAL MARKETS' },
  { id: 6021, descripcion: 'TRUPPEL - GALICIA CAPITAL MARKETS' },
  { id: 6022, descripcion: 'FIRVIDA - GALICIA CAPITAL MARKETS' },
  { id: 6023, descripcion: 'FOSATTI - GALICIA CAPITAL MARKETS' },
  { id: 6024, descripcion: 'GALICIA WARRANTS S.A. - BUENOS AIRES' },
  { id: 6025, descripcion: 'GALICIA WARRANTS S.A. - ENTRE RIOS' },
  { id: 6026, descripcion: 'SANTIAGO SALUD' },
  { id: 6027, descripcion: 'BUENOS AIRES - PROMOPHONE' },
  { id: 6028, descripcion: 'CORDOBA - PROMOPHONE' },
  { id: 6029, descripcion: 'ROSARIO - PROMOPHONE' },
  { id: 6030, descripcion: 'MENDOZA - PROMOPHONE' },
  { id: 6031, descripcion: 'ADMINISTRACIONES FIDUCIARIAS' },
  { id: 6032, descripcion: 'RIVADAVIA 5306' },
  { id: 6033, descripcion: 'AGRO GALICIA' },
  { id: 6034, descripcion: 'GALICIA EQUITY ANALYSIS' },
  { id: 6035, descripcion: 'TARJETAS REGIONALES' },
  { id: 6036, descripcion: 'GRUPO FINANCIERO GALICIA' },
  { id: 6037, descripcion: 'SUDECOR VALORES' },
  { id: 6038, descripcion: 'TRADECOM S.A.' },
  { id: 6039, descripcion: 'NET INVESTMENT GERENCIA' },
  { id: 6040, descripcion: 'GALICIA WARRANTS S.A. - TUCUMAN' },
  { id: 6041, descripcion: 'NET INVESTMENT COMERCIAL' },
  { id: 6042, descripcion: 'NET INVESTMENT SISTEMAS' },
  { id: 6043, descripcion: 'NET INVESTMENT ADMINISTRACION' },
  { id: 6044, descripcion: 'GV MANDATARIA DE VALORES S.A.' },
  { id: 6045, descripcion: 'TARJETAS REGIONALES PROYECTOS' },
  { id: 6046, descripcion: 'EBA HOLDING S.A.' },
  { id: 6047, descripcion: 'GALICIA ADM. DE FONDOS- GFG' },
  { id: 6048, descripcion: 'GALICIA ADM. DE FONDOS - IGAM' },
  { id: 6050, descripcion: 'PROMOPHONE - BUENOS AIRES' },
  { id: 6060, descripcion: 'PROMOTORES' },
  { id: 6061, descripcion: 'TECNOLOGIA' },
  { id: 6062, descripcion: 'ADMINISTRACION' },
  { id: 6063, descripcion: 'MARKETING' },
  { id: 6064, descripcion: 'PROCESOS' },
  { id: 6065, descripcion: 'PROGRAMACION' },
  { id: 6066, descripcion: 'PRODUCCION MULTIMEDIA' },
  { id: 6067, descripcion: 'C. OP. TECNOLOGIA' },
  { id: 6068, descripcion: 'CRM' },
  { id: 6069, descripcion: 'CULTIVOS' },
  { id: 6070, descripcion: 'GERENCIA GENERAL' },
  { id: 6071, descripcion: 'ADMINISTRACION' },
  { id: 6072, descripcion: 'SECCION' },
  { id: 6073, descripcion: 'AGROINSUMOS' },
  { id: 6074, descripcion: 'GRANOS' },
  { id: 6075, descripcion: 'VILA' },
  { id: 6076, descripcion: 'SIERRA' },
  { id: 6077, descripcion: 'ARIAUDO' },
  { id: 6078, descripcion: 'CAMPOS' },
  { id: 6079, descripcion: 'TRO' },
  { id: 6080, descripcion: 'GOTI' },
  { id: 6100, descripcion: 'MARIN' },
  { id: 7000, descripcion: 'AC-AdministracionyFinanzas' },
  { id: 7001, descripcion: 'AC-Operaciones' },
  { id: 7002, descripcion: 'AC-OyM' },
  { id: 7003, descripcion: 'Adm de CrÃ©d / CC CFA' },
  { id: 7004, descripcion: 'Adm de CrÃ©d Cta Si - CC CFA' },
  { id: 7005, descripcion: 'Adm de CrÃ©d Riesgos - CC CFA' },
  { id: 7006, descripcion: 'ADM. DE COBRANZAS' },
  { id: 7007, descripcion: 'ADMINISTRACION COBRANZAS TARJETAS' },
  { id: 7008, descripcion: 'Administración Crédito Cuota SA­' },
  { id: 7009, descripcion: 'ADMINISTRACION DE CREDITOS A EFECTIVO' },
  { id: 7010, descripcion: 'ADMINISTRACION DE CREDITOS A MUTUALES' },
  { id: 7011, descripcion: 'ADMINISTRACION GENERAL' },
  { id: 7012, descripcion: 'Analisis. de Cartera y MIS' },
  { id: 7013, descripcion: 'Area de Soporte de AS/400' },
  { id: 7014, descripcion: 'Asignacion Gastos PR' },
  { id: 7015, descripcion: 'Asis de Gcia Gral - CC CFA' },
  { id: 7016, descripcion: 'Back Office de TDM' },
  { id: 7017, descripcion: 'Casa Central - Procesamiento Tarjetas' },
  { id: 7018, descripcion: 'CENTRO DE COMPUTOS' },
  { id: 7019, descripcion: 'Comunic. / UPC - CC CFA' },
  { id: 7020, descripcion: 'Comununicaciones - CC CFA' },
  { id: 7021, descripcion: 'CONTROL PRESUPUESTARIO' },
  { id: 7022, descripcion: 'Ctrl Inf - CDI - Cta Si - Venezuela' },
  { id: 7023, descripcion: 'Ctrl Inf - CDI / Venezuela' },
  { id: 7024, descripcion: 'Cuentas a Pagar' },
  { id: 7025, descripcion: 'Data mining' },
  { id: 7026, descripcion: 'Data Mining - CC CFA' },
  { id: 7027, descripcion: 'Departamento de Arquitectura de Sistema' },
  { id: 7028, descripcion: 'Departamento de OrganizaciÃ³n y MÃ©todos' },
  { id: 7029, descripcion: 'DEPTO. CONTROL DE RIESGO' },
  { id: 7030, descripcion: 'DESARROLLO' },
  { id: 7031, descripcion: 'Dpto de Datawarehouse' },
  { id: 7032, descripcion: 'Dpto de Desarrollo de Aplicaciones' },
  { id: 7033, descripcion: 'Dpto de Desarrollo y Mant de Windows' },
  { id: 7034, descripcion: 'Dpto de Desarrollo y Mantenimiento' },
  { id: 7035, descripcion: 'Dpto de Serv de TecnologÃ­a' },
  { id: 7036, descripcion: 'Dpto Region Latinoamericana' },
  { id: 7037, descripcion: 'Dpto. de Normas y Procedimientos' },
  { id: 7038, descripcion: 'Dpto. de Quality Assurance' },
  { id: 7039, descripcion: 'Dto. Legales - CyS' },
  { id: 7040, descripcion: 'FISERV' },
  { id: 7041, descripcion: 'Gcia. de Planeamiento y Reportes' },
  { id: 7042, descripcion: 'Gerencia de Business Analytics' },
  { id: 7043, descripcion: 'Gerencia de Servicios de Tarjetas' },
  { id: 7044, descripcion: 'Gerencia de Servicios IT' },
  { id: 7045, descripcion: 'GERENCIA DE SISTEMAS' },
  { id: 7046, descripcion: 'Gerencia General' },
  { id: 7047, descripcion: 'Gerencia General - CC CFA' },
  { id: 7048, descripcion: 'Gerencia PR' },
  { id: 7049, descripcion: 'Gestión de la Demanda' },
  { id: 7050, descripcion: 'Help Desk - CC CFA' },
  { id: 7051, descripcion: 'Help Desk / TDM' },
  { id: 7052, descripcion: 'Infraestructura - CC CFA' },
  { id: 7053, descripcion: 'Infraestructura / TDM' },
  { id: 7054, descripcion: 'Infraestructura RPC' },
  { id: 7055, descripcion: 'LA-Ushuaia' },
  { id: 7056, descripcion: 'Mant. de Sistemas - CC CFA' },
  { id: 7057, descripcion: 'Operaciones' },
  { id: 7058, descripcion: 'Operation Control' },
  { id: 7059, descripcion: 'Operations Control - CC CFA' },
  { id: 7060, descripcion: 'Org y MAtodos - CC CFA' },
  { id: 7061, descripcion: 'ORGANIZACION Y METODOS' },
  { id: 7062, descripcion: 'Plan - Ctrl Gest - Finanzas / TDM' },
  { id: 7063, descripcion: 'Plan - Ctrol Gestión' },
  { id: 7064, descripcion: 'Plat. Com - R.Com / Avellaneda' },
  { id: 7065, descripcion: 'Proces de Datos - CC CFA' },
  { id: 7066, descripcion: 'Proyecto Sistemas - CC CFA' },
  { id: 7067, descripcion: 'Proyectos' },
  { id: 7068, descripcion: 'Proyectos - TDM' },
  { id: 7069, descripcion: 'Proyectos IT' },
  { id: 7070, descripcion: 'QUALITY CONTROL' },
  { id: 7071, descripcion: 'Red Comercial' },
  { id: 7072, descripcion: 'Regional UPC - CC CFA' },
  { id: 7073, descripcion: 'Riesgo Financiero y Unidad Antilavado' },
  { id: 7074, descripcion: 'RR HH' },
  { id: 7075, descripcion: 'SECRETARIA ADM. GENERAL' },
  { id: 7076, descripcion: 'Seg Informática / UPC - CC CFA' },
  { id: 7077, descripcion: 'Seguridad informática' },
  { id: 7078, descripcion: 'Seguridad informática - CC CFA' },
  { id: 7079, descripcion: 'Seguridad Informática / TDM' },
  { id: 7080, descripcion: 'Sistemas - CC CFA' },
  { id: 7081, descripcion: 'Sistemas Proyectos' },
  { id: 7082, descripcion: 'Tarjetas de Crédito' },
  { id: 7083, descripcion: 'Tarjetas del Mar' },
  { id: 7084, descripcion: 'Tarjetas Regionales Cordoba-Proc.Tarj.' },
  { id: 7085, descripcion: 'Tecnologia y Comunicaciones' },
  { id: 7086, descripcion: 'TELEMARKETING' },
  { id: 7087, descripcion: 'Telemarketing - CC CFA' },
  { id: 7777, descripcion: 'PRUEBA CC POR JUAN GRABOSCH.666' },
  { id: 8000, descripcion: 'PLAN DE CARRERA' },
  { id: 8003, descripcion: 'E-COMMERCE' },
  { id: 8005, descripcion: 'GCIA DIVISION MAYORISTA' },
  { id: 8006, descripcion: 'ADM.DE FONDOS DE JUBIL.Y PENSIONES' },
  { id: 8008, descripcion: 'CORRESPONDENCIA' },
  { id: 8009, descripcion: 'CTAS CTES PUBLICO' },
  { id: 8011, descripcion: 'G CREDITOS - AGROP.' },
  { id: 8012, descripcion: 'BALANCES' },
  { id: 8013, descripcion: 'G CRED-D COM Y SERV' },
  { id: 8014, descripcion: 'CREDITOS DE IMPORTACION' },
  { id: 8016, descripcion: 'DESCUENTOS' },
  { id: 8017, descripcion: 'GCIA. INMOBILIARIA' },
  { id: 8018, descripcion: 'RELAC. C/PERSONAL' },
  { id: 8019, descripcion: 'DPTO.OPERATIVO CREDITO' },
  { id: 8023, descripcion: 'CONCIL. SALDOS EXT.' },
  { id: 8024, descripcion: 'DOCUMENTOS EMBARQUE' },
  { id: 8025, descripcion: 'GCIA. ADMINISTRATIVA' },
  { id: 8028, descripcion: 'HIPOTECAS' },
  { id: 8035, descripcion: 'PRIVATE BANKING' },
  { id: 8036, descripcion: 'PROMOCION' },
  { id: 8040, descripcion: 'MAQUINA 2000' },
  { id: 8041, descripcion: 'TIEMPO COMPARTIDO' },
  { id: 8042, descripcion: 'S.OPER.DTO.INMOBILIARIO' },
  { id: 8043, descripcion: 'AMERICAN EXPRESS' },
  { id: 8048, descripcion: 'TESORO DE BOEDO' },
  { id: 8050, descripcion: 'G. COMERC SUCURSALES' },
  { id: 8051, descripcion: 'G COM SUCS-PROM NEG' },
  { id: 8054, descripcion: 'VENTAS ADMINISTRAC.' },
  { id: 8055, descripcion: 'COBRANZAS DE IMPORTACION' },
  { id: 8059, descripcion: 'REL. CORRESP. INT.' },
  { id: 8060, descripcion: 'GCIA. INSPECCION' },
  { id: 8061, descripcion: 'LIQUIDAC. EXTERIOR' },
  { id: 8063, descripcion: 'COBRANZAS INMOBIL.' },
  { id: 8064, descripcion: 'GIROS' },
  { id: 8067, descripcion: 'OFICINA 67' },
  { id: 8068, descripcion: 'OFICINA 68' },
  { id: 8070, descripcion: 'GCIA. CCIAL. INMOB.' },
  { id: 8073, descripcion: 'Desconocido 8073' },
  { id: 8077, descripcion: 'REG. SALDOS TN' },
  { id: 8084, descripcion: 'OTRAS EMPRESAS VINCULADAS' },
  { id: 8085, descripcion: 'PRODUCCION DE SEGUROS' },
  { id: 8086, descripcion: 'INVESTIG. ECONOMICAS' },
  { id: 8087, descripcion: 'CONCILIACIONES' },
  { id: 8092, descripcion: 'CONTROL MOROSIDAD' },
  { id: 8093, descripcion: 'PROGRAMA CRM' },
  { id: 8096, descripcion: 'EMISION DE CHEQUES' },
  { id: 8099, descripcion: 'OFICINA TELEBANCO' },
  { id: 8100, descripcion: 'DEPTO NUEVOS CLIENTES' },
  { id: 8105, descripcion: 'ADMINISTRACION DE FONDOS' },
  { id: 8108, descripcion: 'G NEG EMPRESARIOS' },
  { id: 8112, descripcion: 'BANCA AUTOMATICA' },
  { id: 8115, descripcion: 'GCIA.DIVISION MINORISTA' },
  { id: 8116, descripcion: 'BASE DE CLIENTES' },
  { id: 8124, descripcion: 'CONTROL DE GESTION' },
  { id: 8128, descripcion: 'TRADING' },
  { id: 8129, descripcion: 'OPERACIONES MASIVAS' },
  { id: 8133, descripcion: 'ANTERIOR SUC 133' },
  { id: 8154, descripcion: 'D.O. - REGISTRO SALDOS T N' },
  { id: 8155, descripcion: 'G COM SUCS-CM-AT PUBLI' },
  { id: 8156, descripcion: 'D.O. - T PREVIOS T M' },
  { id: 8157, descripcion: 'G COM SUCS-CM-CAJA' },
  { id: 8159, descripcion: 'G COM SUCS-CM-C SEG.' },
  { id: 8160, descripcion: 'D.O. - SERVICIOS ESPECIALES' },
  { id: 8163, descripcion: 'G COM SUCS-CM-S OPERAT' },
  { id: 8164, descripcion: 'CENTRO ATENC.CONSULTA FILIALES' },
  { id: 8173, descripcion: 'STOCK,ABAST. E INVENT.' },
  { id: 8181, descripcion: 'OPERACIONES' },
  { id: 8182, descripcion: 'PROMOCION' },
  { id: 8183, descripcion: 'REGIONAL METROPOLITANAS' },
  { id: 8184, descripcion: 'ZONA I' },
  { id: 8185, descripcion: 'ZONA V' },
  { id: 8186, descripcion: 'ZONA III' },
  { id: 8187, descripcion: 'ZONA IV' },
  { id: 8188, descripcion: 'G SUC - ZONAL VIII' },
  { id: 8189, descripcion: 'G SUC - ZONAL IX' },
  { id: 8190, descripcion: 'REGIONAL DEL INTERIOR' },
  { id: 8191, descripcion: 'ZONA V' },
  { id: 8192, descripcion: 'ZONA VI' },
  { id: 8193, descripcion: 'ZONA II' },
  { id: 8194, descripcion: 'G SUC - ZONAL XIV' },
  { id: 8195, descripcion: 'ZONA II' },
  { id: 8201, descripcion: 'ASUNTOS LEGALES' },
  { id: 8202, descripcion: 'CAJA CTAS. CTES.' },
  { id: 8203, descripcion: 'CAMBIOS' },
  { id: 8204, descripcion: 'TRAMITES PREVIOS TM' },
  { id: 8205, descripcion: 'CLEARING' },
  { id: 8206, descripcion: 'COBRANZAS Y GIROS' },
  { id: 8207, descripcion: 'GCIA. CONTADURIA' },
  { id: 8210, descripcion: 'DESCUENTOS' },
  { id: 8211, descripcion: 'EXPORTACION' },
  { id: 8213, descripcion: 'CONCILIAC. DE SALDOS' },
  { id: 8214, descripcion: 'IMPORTACION' },
  { id: 8215, descripcion: 'INFORMES' },
  { id: 8216, descripcion: 'GCIA. DE PERSONAL' },
  { id: 8219, descripcion: 'COMPRAS' },
  { id: 8220, descripcion: 'TITULOS' },
  { id: 8221, descripcion: 'CAJA DE AHORROS' },
  { id: 8222, descripcion: 'DEPTO. DE TERCEROS' },
  { id: 8226, descripcion: 'ARCHIVO' },
  { id: 8227, descripcion: 'AUDIT. Y AS. IMPOS.' },
  { id: 8229, descripcion: 'COMUNICACIONES TM' },
  { id: 8230, descripcion: 'GCIA. TECNICA TN' },
  { id: 8231, descripcion: 'CTAS. CTES. TN' },
  { id: 8232, descripcion: 'CUSTODIA VALORES' },
  { id: 8233, descripcion: 'SECR. DIRECTORIO' },
  { id: 8234, descripcion: 'GCIA. DE CREDITOS' },
  { id: 8235, descripcion: 'GCIA. ORGANIZACION' },
  { id: 8236, descripcion: 'GCIA. COMERCIAL SUC' },
  { id: 8237, descripcion: 'GCIA. SUCURSALES' },
  { id: 8238, descripcion: 'LIBRERIA' },
  { id: 8239, descripcion: 'F.I.M.A.' },
  { id: 8241, descripcion: 'MOYORDOMIA' },
  { id: 8242, descripcion: 'MICROFILM TT' },
  { id: 8244, descripcion: 'REGISTRO SALDOS TM' },
  { id: 8245, descripcion: 'REGISTRO SALDOS TTNA' },
  { id: 8246, descripcion: 'FINANCIACIONES EXTERIOR' },
  { id: 8247, descripcion: 'SERVICIO MILITAR' },
  { id: 8248, descripcion: 'APOYO AUTOMATIZACION FILIALES' },
  { id: 8249, descripcion: 'SEGURIDAD' },
  { id: 8250, descripcion: 'VARIOS' },
  { id: 8251, descripcion: 'COMPUTADOR' },
  { id: 8252, descripcion: 'TESORO DE REMESAS' },
  { id: 8253, descripcion: 'COORD. TRANSP. VAL.' },
  { id: 8256, descripcion: 'GERENCIA DE EXTERIOR' },
  { id: 8257, descripcion: 'GCIA. OPERACIONES' },
  { id: 8258, descripcion: 'MAQ Y COMUNICACIONES' },
  { id: 8259, descripcion: 'SOPORTE BASE DE DATOS' },
  { id: 8262, descripcion: 'MANTEN. Y PROYECTOS' },
  { id: 8265, descripcion: 'COB. CUOTAS E HIP.' },
  { id: 8266, descripcion: 'GCIA. OP. CREDITO' },
  { id: 8269, descripcion: 'GARANTIAS' },
  { id: 8271, descripcion: 'GCIA DE NEGOCIOS INM.' },
  { id: 8272, descripcion: 'GCIA. INVERSIONES' },
  { id: 8273, descripcion: 'GCIA. DE PRODUCTO' },
  { id: 8274, descripcion: 'DTO A. Y C. DE RIESGO' },
  { id: 8275, descripcion: 'GCIA. NEG. EXTERIOR' },
  { id: 8276, descripcion: 'INTENDENCIA' },
  { id: 8278, descripcion: 'COMUNICACIONES TT' },
  { id: 8279, descripcion: 'MICROFILM TM' },
  { id: 8280, descripcion: 'TRAMITES PREVIOS TT' },
  { id: 8281, descripcion: 'LIQUIDAC. DE HABERES' },
  { id: 8282, descripcion: 'G.ADM.-GCIA. TECNICA' },
  { id: 8283, descripcion: 'SERV. DIV. G.TECNICA' },
  { id: 8284, descripcion: 'CLAVES' },
  { id: 8285, descripcion: 'SUELDOS SUSPENDIDOS' },
  { id: 8286, descripcion: 'MESA DE CAMBIO' },
  { id: 8287, descripcion: 'DPTO.OPERAC.FINANCIERAS' },
  { id: 8288, descripcion: 'GRANDES EMPRESAS' },
  { id: 8289, descripcion: 'RELAC. EXT Y PUBLIC.' },
  { id: 8290, descripcion: 'PLAN RETIRO' },
  { id: 8291, descripcion: 'SERV.-VS.-R.MEJ.-TEC' },
  { id: 8292, descripcion: 'CONTADURIA-SECT ADM.' },
  { id: 8293, descripcion: 'BALANCES Y REVALUO' },
  { id: 8294, descripcion: 'EFECTIVO MINIMO' },
  { id: 8295, descripcion: 'INVENTARIOS' },
  { id: 8297, descripcion: 'CONTROL REG. CONT.' },
  { id: 8298, descripcion: 'GCIA.PLANEAM. Y C.G.' },
  { id: 8299, descripcion: 'PERSONAL TECNICO' },
  { id: 8301, descripcion: 'SEGUROS' },
  { id: 8302, descripcion: 'CAPACITACION' },
  { id: 8303, descripcion: 'ANALISIS D/RESULTADOS' },
  { id: 8304, descripcion: 'LIBRANZA DE CHEQUES' },
  { id: 8306, descripcion: 'DEUDORES EN SITUAC IRREG' },
  { id: 8307, descripcion: 'DEPTO DE PARTICULARES' },
  { id: 8308, descripcion: 'CAJAS DE SEGURIDAD' },
  { id: 8309, descripcion: 'LICENCIA GREMIAL' },
  { id: 8310, descripcion: 'PLANEAMIENTO Y CONTROL DE GESTIÃ“N' },
  { id: 8322, descripcion: 'ADM SEG INFORMATICA' },
  { id: 8335, descripcion: 'G NEGOC EMPRESARIALES' },
  { id: 8352, descripcion: 'INSTITUCIONALES BID' },
  { id: 8353, descripcion: 'CONTROL CALIDAD' },
  { id: 8354, descripcion: 'SOPORTE COMPUTADOR CENTRAL' },
  { id: 8355, descripcion: 'PROYECTOS ESPECIALES' },
  { id: 8380, descripcion: 'CASA BANCARIA' },
  { id: 8381, descripcion: 'CIFEBA' },
  { id: 8382, descripcion: 'INVICTUS' },
  { id: 8388, descripcion: 'COLOCACION TITULOS PRIVADOS' },
  { id: 8393, descripcion: 'REGION INTERIOR 1' },
  { id: 8408, descripcion: 'DPTO BANCA DE INVERSION' },
  { id: 8409, descripcion: 'RIESGO FINANCIERO' },
  { id: 8412, descripcion: 'G CREDITOS - INDUST' },
  { id: 8413, descripcion: 'G CREDITOS - COMERC' },
  { id: 8414, descripcion: 'G CREDITOS - CONST' },
  { id: 8423, descripcion: 'PY REGIONAL CORDOBA' },
  { id: 8424, descripcion: 'PY REGIONAL CUYO' },
  { id: 8425, descripcion: 'PY REGIONAL SANTA FE' },
  { id: 8430, descripcion: 'DPTO INFRAEST Y MANTEN' },
  { id: 8432, descripcion: 'AGRO REGIONAL' },
  { id: 8433, descripcion: 'AGRO METROPOLITANA' },
  { id: 8436, descripcion: 'CTRO.ATENC.USUAR.TECNOLOGIA' },
  { id: 8441, descripcion: 'P.C.O. CENTRAL' },
  { id: 8449, descripcion: 'PERS.TRANST.AFECT.A PROYECTOS' },
  { id: 8450, descripcion: 'G COMERC SUCURSALES' },
  { id: 8451, descripcion: 'G COM SUCS-PROM NEG' },
  { id: 8455, descripcion: 'G COM SUCS-CM-C AHOR' },
  { id: 8456, descripcion: 'G COM SUCS-CM-C CTES' },
  { id: 8457, descripcion: 'D.O. - T PREVIOS T T' },
  { id: 8458, descripcion: 'G COM SUCS-CM-COBRAN' },
  { id: 8464, descripcion: 'G PERS-LIQ DE HABERES' },
  { id: 8470, descripcion: 'DPTO CREDITOS MINORISTAS' },
  { id: 8480, descripcion: 'G NEGOCIO EXTERIOR' },
  { id: 8488, descripcion: 'X' },
  { id: 8489, descripcion: 'COLOCACION DE ACCIONES DE SEVEL' },
  { id: 8512, descripcion: 'G CRED-D IND Y CONST' },
  { id: 8514, descripcion: 'G CRED-D DE SUCURS' },
  { id: 8520, descripcion: 'G OPERAT EXTERIOR' },
  { id: 8550, descripcion: 'DPTO SERVICIOS A EMPRESAS' },
  { id: 8561, descripcion: 'G O-VAL MOBILIARIOS' },
  { id: 8562, descripcion: 'G O-TESORO' },
  { id: 8580, descripcion: 'G OPER DE SUCURSALES' },
  { id: 8600, descripcion: 'G CONT EFIC OPERATIV' },
  { id: 8620, descripcion: 'G TECNICA' },
  { id: 8621, descripcion: 'G TEC-COMPRAS Y ADM' },
  { id: 8622, descripcion: 'G TEC-INVENTARIOS' },
  { id: 8623, descripcion: 'G TEC-ING ARQ Y MANT' },
  { id: 8624, descripcion: 'G TEC-MAQUIN Y COMUN' },
  { id: 8625, descripcion: 'G TEC-INTENDENCIA' },
  { id: 8626, descripcion: 'G TEC-LIBRERIA' },
  { id: 8627, descripcion: 'G TEC-ARCHIVO' },
  { id: 8628, descripcion: 'G TEC-SERV DIVERSOS' },
  { id: 8629, descripcion: 'G TEC-DEPOSITO R M' },
  { id: 8630, descripcion: 'AUTOMOTORES' },
  { id: 8642, descripcion: 'NORMAS Y PROCEDIMIENTOS' },
  { id: 8645, descripcion: 'DESARROLLO Y MANTENIMIENTO DE SISTEMAS' },
  { id: 8666, descripcion: 'Desconocido 8666' },
  { id: 8680, descripcion: 'GCIA DIVISION FINANZAS' },
  { id: 8683, descripcion: 'FONDOS DE INVERSION' },
  { id: 8689, descripcion: 'UAC (UNIDAD ADMINITR.CENTRALIZADA)' },
  { id: 8711, descripcion: 'G CREDITOS - AGROP.' },
  { id: 8712, descripcion: 'G CRED-D IND Y CONST' },
  { id: 8713, descripcion: 'G CRED-D COM Y SERV' },
  { id: 8714, descripcion: 'G CRED-D DE SUCURS' },
  { id: 8726, descripcion: 'LIC. GREMIAL II' },
  { id: 8727, descripcion: 'LIC. GREMIAL' },
  { id: 8750, descripcion: 'G OPERACIONES' },
  { id: 8753, descripcion: 'VENDIMIA' },
  { id: 8754, descripcion: 'G O-CTAS CTES T N' },
  { id: 8755, descripcion: 'G O-COMPUTADOR' },
  { id: 8758, descripcion: 'G O-COMUNICACIONES' },
  { id: 8760, descripcion: 'G O-MICROFILM' },
  { id: 8763, descripcion: 'G O-SUPERV BANELCO' },
  { id: 8764, descripcion: 'G O-BANCA ELECTRONICA' },
  { id: 8771, descripcion: 'G A-SECTOR ADM' },
  { id: 8772, descripcion: 'G A-INTENDENCIA' },
  { id: 8773, descripcion: 'G A-LIBRERIA' },
  { id: 8774, descripcion: 'G A-ARCHIVO' },
  { id: 8800, descripcion: 'G DE PRODUCTOS' },
  { id: 8805, descripcion: 'G AREA COMERCIAL' },
  { id: 8815, descripcion: 'G AREA OPERATIVA' },
  { id: 8818, descripcion: 'DPTO INV Y PLAN TECN' },
  { id: 8830, descripcion: 'GERENCIA TECNICA' },
  { id: 8831, descripcion: 'G TEC-INVERS Y PRESUP' },
  { id: 8832, descripcion: 'G TEC-ARQUITECTURA' },
  { id: 8833, descripcion: 'G TEC-ING Y MANTEN' },
  { id: 8834, descripcion: 'G TEC-ELECTROMECANICA' },
  { id: 8835, descripcion: 'G TEC-MAQUINAS Y EQUIPOS' },
  { id: 8836, descripcion: 'G TEC-TELECOMUNICACIONES' },
  { id: 8837, descripcion: 'G TEC-RODADOS' },
  { id: 8840, descripcion: 'GCIA DE ORGANIZACION' },
  { id: 8841, descripcion: 'G ORG-ANALISIS Y PROG' },
  { id: 8842, descripcion: 'G ORG-NORMAS Y PROCED' },
  { id: 8843, descripcion: 'G ORG-APOYO SIST GALM' },
  { id: 8844, descripcion: 'G ORG-APOYO SANT COMP' },
  { id: 8845, descripcion: 'G ORG-SISTEMA SITAB' },
  { id: 8850, descripcion: 'PERSONAL TECNICO' },
  { id: 8860, descripcion: 'GCIA DE PERSONAL' },
  { id: 8861, descripcion: 'G PERS-CAPACITACION' },
  { id: 8862, descripcion: 'G PERS-BIBLIOTECA' },
  { id: 8863, descripcion: 'G PERS-POSTULANTES' },
  { id: 8864, descripcion: 'G PERS-C I C' },
  { id: 8881, descripcion: 'G PLANEAMIENTO FINANCIERO' },
  { id: 8882, descripcion: 'G OPERACIONES FINANCIERAS' },
  { id: 8886, descripcion: 'SERVICIO MILITAR' },
  { id: 8888, descripcion: 'PRUEBA CC POR JUAN GRABOSCH.666' },
  { id: 8889, descripcion: 'O.S.N.' },
  { id: 8915, descripcion: 'G AREA SERVICIOS' },
  { id: 8922, descripcion: 'ADM SEG INFORMATICA' },
  { id: 8960, descripcion: 'G O-MICROFILM TM' },
  { id: 8963, descripcion: 'G O-SUPERV BANELCO' },
  { id: 8964, descripcion: 'BANCA ELECTRONICA' },
  { id: 8981, descripcion: 'G SUC- ZONAL I' },
  { id: 8982, descripcion: 'G SUC- ZONAL II' },
  { id: 8983, descripcion: 'G SUC- ZONAL III' },
  { id: 8984, descripcion: 'G SUC- ZONAL IV' },
  { id: 8985, descripcion: 'G SUC- ZONAL V' },
  { id: 8986, descripcion: 'G SUC- ZONAL VI' },
  { id: 8987, descripcion: 'G SUC- ZONAL VII' },
  { id: 8990, descripcion: 'G SUC- ZONAL X' },
  { id: 8991, descripcion: 'G SUC- ZONAL XI' },
  { id: 8992, descripcion: 'G SUC- ZONAL XII' },
  { id: 8993, descripcion: 'G SUC- ZONAL XIII' },
  { id: 8999, descripcion: 'CASA MATRIZ' },
  { id: 9012, descripcion: 'SALDIAS' },
  { id: 9013, descripcion: 'MERCADO DE HACIENDA' },
  { id: 9024, descripcion: 'PARQUE CHACABUCO' },
  { id: 9031, descripcion: 'VILLA LURO' },
  { id: 9034, descripcion: 'MATADEROS' },
  { id: 9052, descripcion: 'LA LUCILA' },
  { id: 9064, descripcion: 'LA PLATA' },
  { id: 9065, descripcion: 'CHACARITA' },
  { id: 9068, descripcion: 'VILLA REAL' },
  { id: 9073, descripcion: 'SALTA' },
  { id: 9085, descripcion: 'BARILOCHE' },
  { id: 9087, descripcion: 'NUÑEZ NORTE' },
  { id: 9099, descripcion: 'NECOCHEA' },
  { id: 9108, descripcion: 'Desconocido 9108' },
  { id: 9112, descripcion: '9112' },
  { id: 9125, descripcion: 'BOULEVARD OROÑO' },
  { id: 9127, descripcion: 'WARNES' },
  { id: 9128, descripcion: 'AZCUENAGA' },
  { id: 9131, descripcion: 'MATADEROS' },
  { id: 9133, descripcion: 'LINCOLN' },
  { id: 9134, descripcion: 'BELGRANO' },
  { id: 9145, descripcion: 'MIGUEL LILLO' },
  { id: 9147, descripcion: 'MIRAMAR' },
  { id: 9161, descripcion: 'QUILMES' },
  { id: 9163, descripcion: 'VILLA DEVOTO NORTE' },
  { id: 9164, descripcion: 'SAN MARTIN CENTRO' },
  { id: 9167, descripcion: 'LA BANDA' },
  { id: 9169, descripcion: 'CHAJARI' },
  { id: 9174, descripcion: 'MENDOZA' },
  { id: 9175, descripcion: 'SALTO - BS. AS.' },
  { id: 9213, descripcion: 'FLORESTA' },
  { id: 9288, descripcion: 'DATA ROOM' },
  { id: 9501, descripcion: 'U OPERATIVA CORDOBA' },
  { id: 9503, descripcion: 'U O MAR DEL PLATA' },
  { id: 9505, descripcion: 'U O ROSARIO' },
  { id: 9506, descripcion: 'U O SALTA' },
  { id: 9868, descripcion: 'PRUEBA CC POR JUAN GRABOSCH.777' },
  { id: 9869, descripcion: 'PRUEBA CC POR JUAN GRABOSCH.123' },
  { id: 9872, descripcion: 'PROYECTOS ESPECIALES - BANCA MAYORISTA' },
  { id: 9873, descripcion: 'PROYECTOS ESPECIALES - BANCA MAYORISTA' },
  { id: 9874, descripcion: 'PROYECTOS ESPECIALES - BANCA MAYORISTA' },
  { id: 9875, descripcion: 'PROYECTOS ESPECIALES - BANCA MAYORISTA' },
  { id: 9876, descripcion: 'PROYECTOS ESPECIALES - BANCA MAYORISTA' },
  { id: 9997, descripcion: 'PRUEBA' },
  { id: 9998, descripcion: 'PRUEBA' },
  { id: 9999, descripcion: 'SUCURSALES' },
  { id: 10000, descripcion: 'Centro de costo 10000' },
  { id: 10001, descripcion: 'Centro de costo 10001' },
  { id: 10002, descripcion: 'Centro de costo 10002' },
  { id: 10003, descripcion: 'Centro de costo 10003' },
  { id: 10004, descripcion: 'Centro de costo 10004' },
  { id: 10005, descripcion: 'Centro de costo 10005' },
  { id: 10006, descripcion: 'Centro de costo 10006' },
];
